import { useState, useMemo } from 'preact/hooks';

type Position = 'bottom-bar' | 'bottom-left' | 'bottom-right' | 'top-bar';
type Theme = 'dark' | 'light' | 'minimal';

interface CookieCategory {
  id: string;
  name: string;
  description: string;
  required: boolean;
  enabled: boolean;
}

const DEFAULT_CATEGORIES: CookieCategory[] = [
  { id: 'necessary', name: 'Necessary', description: 'Essential for the website to function properly.', required: true, enabled: true },
  { id: 'analytics', name: 'Analytics', description: 'Help us understand how visitors interact with our website.', required: false, enabled: false },
  { id: 'marketing', name: 'Marketing', description: 'Used to track visitors across websites for advertising purposes.', required: false, enabled: false },
  { id: 'preferences', name: 'Preferences', description: 'Allow the website to remember choices you make (language, region).', required: false, enabled: false },
];

const THEME_STYLES: Record<Theme, { bg: string; text: string; muted: string; btn: string; btnText: string; border: string }> = {
  dark: { bg: '#1a1a2e', text: '#e2e2e2', muted: '#888', btn: '#4f46e5', btnText: '#fff', border: '#333' },
  light: { bg: '#ffffff', text: '#111827', muted: '#6b7280', btn: '#4f46e5', btnText: '#fff', border: '#e5e7eb' },
  minimal: { bg: '#f9fafb', text: '#111827', muted: '#6b7280', btn: '#111827', btnText: '#fff', border: '#d1d5db' },
};

export default function CookieConsentGenerator() {
  const [position, setPosition] = useState<Position>('bottom-bar');
  const [theme, setTheme] = useState<Theme>('dark');
  const [showCategories, setShowCategories] = useState(true);
  const [showDecline, setShowDecline] = useState(true);
  const [policyUrl, setPolicyUrl] = useState('/privacy-policy');
  const [companyName, setCompanyName] = useState('Your Company');
  const [categories, setCategories] = useState<CookieCategory[]>(DEFAULT_CATEGORIES);
  const [copied, setCopied] = useState(false);

  function toggleCategory(id: string) {
    setCategories(cats => cats.map(c => c.id === id && !c.required ? { ...c, enabled: !c.enabled } : c));
  }

  const s = THEME_STYLES[theme];

  const positionStyle: Record<Position, string> = {
    'bottom-bar': 'position:fixed;bottom:0;left:0;right:0;',
    'bottom-left': 'position:fixed;bottom:16px;left:16px;max-width:380px;border-radius:12px;',
    'bottom-right': 'position:fixed;bottom:16px;right:16px;max-width:380px;border-radius:12px;',
    'top-bar': 'position:fixed;top:0;left:0;right:0;',
  };

  const categoriesHtml = useMemo(() => {
    if (!showCategories) return '';
    return `
  <div id="cc-categories" style="display:none;margin-top:10px;border-top:1px solid ${s.border};padding-top:10px;">
${categories.map(c => `    <label style="display:flex;align-items:flex-start;gap:8px;margin-bottom:8px;cursor:${c.required ? 'default' : 'pointer'};">
      <input type="checkbox" id="cc-${c.id}" ${c.required || c.enabled ? 'checked' : ''} ${c.required ? 'disabled' : ''} style="margin-top:2px;">
      <span>
        <strong style="color:${s.text};font-size:13px;">${c.name}${c.required ? ' (required)' : ''}</strong>
        <span style="display:block;color:${s.muted};font-size:12px;">${c.description}</span>
      </span>
    </label>`).join('\n')}
  </div>
  <button onclick="document.getElementById('cc-categories').style.display=document.getElementById('cc-categories').style.display==='none'?'block':'none'" style="background:none;border:none;color:${s.muted};font-size:12px;cursor:pointer;padding:0;margin-top:4px;text-decoration:underline;">Manage preferences</button>`;
  }, [categories, showCategories, s]);

  const declineBtn = showDecline
    ? `<button onclick="ccDecline()" style="background:none;border:1px solid ${s.border};color:${s.text};padding:8px 16px;border-radius:6px;cursor:pointer;font-size:14px;">Decline</button>`
    : '';

  const html = useMemo(() => `<!-- Cookie Consent Banner — generated by DevPlaybook -->
<div id="cookie-consent" style="${positionStyle[position]}background:${s.bg};color:${s.text};padding:16px 20px;box-shadow:0 -2px 12px rgba(0,0,0,.15);z-index:9999;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:900px;margin:0 auto;">
    <p style="margin:0 0 8px;font-size:14px;line-height:1.5;">
      We use cookies to enhance your experience. By continuing, you agree to our
      <a href="${policyUrl}" style="color:${s.btn};">Privacy Policy</a>.
      ${categoriesHtml}
    </p>
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px;">
      <button onclick="ccAcceptAll()" style="background:${s.btn};color:${s.btnText};border:none;padding:8px 16px;border-radius:6px;cursor:pointer;font-size:14px;font-weight:500;">Accept All</button>
      ${showCategories ? `<button onclick="ccSavePrefs()" style="background:none;border:1px solid ${s.border};color:${s.text};padding:8px 16px;border-radius:6px;cursor:pointer;font-size:14px;">Save Preferences</button>` : ''}
      ${declineBtn}
    </div>
  </div>
</div>

<script>
(function() {
  const CONSENT_KEY = 'cookie_consent_${companyName.toLowerCase().replace(/[^a-z0-9]/g, '_')}';

  function hideBanner() {
    var el = document.getElementById('cookie-consent');
    if (el) el.style.display = 'none';
  }

  function saveConsent(prefs) {
    localStorage.setItem(CONSENT_KEY, JSON.stringify({ ts: Date.now(), prefs: prefs }));
    hideBanner();
    // Fire consent event for GTM / GA4
    if (typeof gtag !== 'undefined') {
      gtag('consent', 'update', {
        analytics_storage: prefs.analytics ? 'granted' : 'denied',
        ad_storage: prefs.marketing ? 'granted' : 'denied',
      });
    }
    document.dispatchEvent(new CustomEvent('cookieConsent', { detail: prefs }));
  }

  window.ccAcceptAll = function() {
    saveConsent({ necessary: true, analytics: true, marketing: true, preferences: true });
  };

  window.ccDecline = function() {
    saveConsent({ necessary: true, analytics: false, marketing: false, preferences: false });
  };

  window.ccSavePrefs = function() {
    var prefs = {};
    ${categories.map(c => `    prefs['${c.id}'] = ${c.required ? 'true' : `!!document.getElementById('cc-${c.id}') && document.getElementById('cc-${c.id}').checked`};`).join('\n')}
    saveConsent(prefs);
  };

  // Hide if already consented
  if (localStorage.getItem(CONSENT_KEY)) {
    hideBanner();
  }
})();
<\/script>`, [position, s, policyUrl, companyName, categoriesHtml, showCategories, declineBtn, categories]);

  async function copyHtml() {
    await navigator.clipboard.writeText(html);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div class="space-y-6">
      {/* Config */}
      <div class="bg-bg-card border border-border rounded-xl p-5">
        <h2 class="text-base font-semibold mb-4">Configuration</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label class="block text-xs text-text-muted mb-1">Company / Site Name</label>
            <input
              class="w-full bg-bg border border-border rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-primary"
              value={companyName}
              onInput={(e) => setCompanyName((e.target as HTMLInputElement).value)}
              placeholder="Your Company"
            />
          </div>
          <div>
            <label class="block text-xs text-text-muted mb-1">Privacy Policy URL</label>
            <input
              class="w-full bg-bg border border-border rounded-lg px-3 py-2 text-sm font-mono focus:ring-2 focus:ring-primary"
              value={policyUrl}
              onInput={(e) => setPolicyUrl((e.target as HTMLInputElement).value)}
              placeholder="/privacy-policy"
            />
          </div>
          <div>
            <label class="block text-xs text-text-muted mb-2">Banner Position</label>
            <div class="grid grid-cols-2 gap-2">
              {([
                { val: 'bottom-bar', label: 'Bottom Bar' },
                { val: 'top-bar', label: 'Top Bar' },
                { val: 'bottom-left', label: 'Bottom Left' },
                { val: 'bottom-right', label: 'Bottom Right' },
              ] as { val: Position; label: string }[]).map(p => (
                <button
                  key={p.val}
                  onClick={() => setPosition(p.val)}
                  class={`text-xs px-3 py-2 rounded-lg border transition-colors ${
                    position === p.val ? 'bg-primary text-white border-primary' : 'bg-bg border-border hover:border-primary text-text-muted'
                  }`}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>
          <div>
            <label class="block text-xs text-text-muted mb-2">Theme</label>
            <div class="flex gap-2">
              {(['dark', 'light', 'minimal'] as Theme[]).map(t => (
                <button
                  key={t}
                  onClick={() => setTheme(t)}
                  class={`text-xs px-3 py-2 rounded-lg border capitalize transition-colors flex-1 ${
                    theme === t ? 'bg-primary text-white border-primary' : 'bg-bg border-border hover:border-primary text-text-muted'
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>
          <div class="flex flex-col gap-3">
            <label class="flex items-center gap-2 cursor-pointer text-sm">
              <input type="checkbox" checked={showCategories} onChange={(e) => setShowCategories((e.target as HTMLInputElement).checked)} class="rounded" />
              Show cookie categories / preferences
            </label>
            <label class="flex items-center gap-2 cursor-pointer text-sm">
              <input type="checkbox" checked={showDecline} onChange={(e) => setShowDecline((e.target as HTMLInputElement).checked)} class="rounded" />
              Show "Decline" button
            </label>
          </div>
        </div>
      </div>

      {/* Categories */}
      {showCategories && (
        <div class="bg-bg-card border border-border rounded-xl p-5">
          <h2 class="text-base font-semibold mb-3">Cookie Categories</h2>
          <div class="space-y-2">
            {categories.map(c => (
              <div key={c.id} class="flex items-start gap-3 bg-bg rounded-lg p-3">
                <input
                  type="checkbox"
                  checked={c.enabled}
                  disabled={c.required}
                  onChange={() => toggleCategory(c.id)}
                  class="mt-0.5"
                />
                <div class="flex-1 min-w-0">
                  <div class="text-sm font-medium">{c.name}{c.required && <span class="text-xs text-text-muted ml-1">(required)</span>}</div>
                  <input
                    class="w-full bg-transparent text-xs text-text-muted mt-0.5 focus:outline-none border-b border-transparent hover:border-border focus:border-primary"
                    value={c.description}
                    onInput={(e) => setCategories(cats => cats.map(cat => cat.id === c.id ? { ...cat, description: (e.target as HTMLInputElement).value } : cat))}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Output */}
      <div class="bg-bg-card border border-border rounded-xl p-5">
        <div class="flex items-center justify-between mb-3">
          <h2 class="text-base font-semibold">Generated HTML/JS</h2>
          <button
            onClick={copyHtml}
            class="text-sm bg-primary hover:bg-primary/80 text-white px-4 py-2 rounded-lg transition-colors"
          >
            {copied ? '✓ Copied!' : 'Copy HTML'}
          </button>
        </div>
        <pre class="bg-bg text-green-400 text-xs rounded-lg p-4 overflow-x-auto font-mono whitespace-pre-wrap">{html}</pre>
        <p class="text-xs text-text-muted mt-3">Paste this snippet just before the <code>&lt;/body&gt;</code> tag. For GDPR compliance, also set up Google Consent Mode v2 defaults in your &lt;head&gt; before GA4 loads.</p>
      </div>
    </div>
  );
}
