import { useState } from 'preact/hooks';

type ChartPreset = 'nginx' | 'postgres' | 'redis' | 'custom';

interface ServicePort {
  name: string;
  port: string;
  targetPort: string;
  protocol: 'TCP' | 'UDP';
}

interface EnvVar {
  name: string;
  value: string;
}

interface HelmConfig {
  replicaCount: string;
  imageRepository: string;
  imageTag: string;
  imagePullPolicy: 'IfNotPresent' | 'Always' | 'Never';
  serviceType: 'ClusterIP' | 'NodePort' | 'LoadBalancer';
  ports: ServicePort[];
  resourcesCpuRequest: string;
  resourcesCpuLimit: string;
  resourcesMemRequest: string;
  resourcesMemLimit: string;
  autoscalingEnabled: boolean;
  autoscalingMinReplicas: string;
  autoscalingMaxReplicas: string;
  autoscalingCpuUtilization: string;
  ingressEnabled: boolean;
  ingressClassName: string;
  ingressHost: string;
  ingressTlsEnabled: boolean;
  envVars: EnvVar[];
  livenessEnabled: boolean;
  livenessPath: string;
  readinessEnabled: boolean;
  readinessPath: string;
  persistenceEnabled: boolean;
  persistenceSize: string;
  persistenceStorageClass: string;
  namespaceOverride: string;
}

const PRESETS: Record<ChartPreset, Partial<HelmConfig>> = {
  nginx: {
    imageRepository: 'nginx',
    imageTag: '1.25-alpine',
    replicaCount: '2',
    ports: [{ name: 'http', port: '80', targetPort: '80', protocol: 'TCP' }],
    serviceType: 'ClusterIP',
    ingressEnabled: true,
    ingressClassName: 'nginx',
    ingressHost: 'app.example.com',
    livenessEnabled: true,
    livenessPath: '/',
    readinessEnabled: true,
    readinessPath: '/',
    resourcesCpuRequest: '50m',
    resourcesCpuLimit: '200m',
    resourcesMemRequest: '64Mi',
    resourcesMemLimit: '128Mi',
  },
  postgres: {
    imageRepository: 'postgres',
    imageTag: '16-alpine',
    replicaCount: '1',
    ports: [{ name: 'postgres', port: '5432', targetPort: '5432', protocol: 'TCP' }],
    serviceType: 'ClusterIP',
    persistenceEnabled: true,
    persistenceSize: '10Gi',
    persistenceStorageClass: 'standard',
    envVars: [
      { name: 'POSTGRES_DB', value: 'myapp' },
      { name: 'POSTGRES_USER', value: 'admin' },
      { name: 'POSTGRES_PASSWORD', value: 'changeme' },
    ],
    resourcesCpuRequest: '100m',
    resourcesCpuLimit: '500m',
    resourcesMemRequest: '256Mi',
    resourcesMemLimit: '512Mi',
  },
  redis: {
    imageRepository: 'redis',
    imageTag: '7-alpine',
    replicaCount: '1',
    ports: [{ name: 'redis', port: '6379', targetPort: '6379', protocol: 'TCP' }],
    serviceType: 'ClusterIP',
    persistenceEnabled: true,
    persistenceSize: '2Gi',
    persistenceStorageClass: 'standard',
    resourcesCpuRequest: '50m',
    resourcesCpuLimit: '200m',
    resourcesMemRequest: '64Mi',
    resourcesMemLimit: '256Mi',
  },
  custom: {
    imageRepository: 'my-registry/my-app',
    imageTag: 'latest',
    replicaCount: '1',
    ports: [{ name: 'http', port: '8080', targetPort: '8080', protocol: 'TCP' }],
    serviceType: 'ClusterIP',
    ingressEnabled: false,
    resourcesCpuRequest: '100m',
    resourcesCpuLimit: '500m',
    resourcesMemRequest: '128Mi',
    resourcesMemLimit: '256Mi',
  },
};

const DEFAULT_CONFIG: HelmConfig = {
  replicaCount: '1',
  imageRepository: 'my-registry/my-app',
  imageTag: 'latest',
  imagePullPolicy: 'IfNotPresent',
  serviceType: 'ClusterIP',
  ports: [{ name: 'http', port: '8080', targetPort: '8080', protocol: 'TCP' }],
  resourcesCpuRequest: '100m',
  resourcesCpuLimit: '500m',
  resourcesMemRequest: '128Mi',
  resourcesMemLimit: '256Mi',
  autoscalingEnabled: false,
  autoscalingMinReplicas: '1',
  autoscalingMaxReplicas: '5',
  autoscalingCpuUtilization: '80',
  ingressEnabled: false,
  ingressClassName: 'nginx',
  ingressHost: 'app.example.com',
  ingressTlsEnabled: false,
  envVars: [],
  livenessEnabled: false,
  livenessPath: '/health',
  readinessEnabled: false,
  readinessPath: '/ready',
  persistenceEnabled: false,
  persistenceSize: '5Gi',
  persistenceStorageClass: 'standard',
  namespaceOverride: '',
};

let envIdSeq = 0;
function uid() { return `e${++envIdSeq}`; }

function generateValuesYaml(cfg: HelmConfig): string {
  const lines: string[] = [];

  lines.push(`# Helm values.yaml — generated by DevPlaybook`);
  lines.push(`# https://devplaybook.cc/tools/helm-values-generator`);
  lines.push('');

  if (cfg.namespaceOverride) {
    lines.push(`namespaceOverride: "${cfg.namespaceOverride}"`);
    lines.push('');
  }

  lines.push(`replicaCount: ${cfg.replicaCount}`);
  lines.push('');

  lines.push('image:');
  lines.push(`  repository: ${cfg.imageRepository}`);
  lines.push(`  tag: "${cfg.imageTag}"`);
  lines.push(`  pullPolicy: ${cfg.imagePullPolicy}`);
  lines.push('');

  lines.push('service:');
  lines.push(`  type: ${cfg.serviceType}`);
  if (cfg.ports.length > 0) {
    lines.push('  ports:');
    for (const p of cfg.ports) {
      lines.push(`    - name: ${p.name}`);
      lines.push(`      port: ${p.port}`);
      lines.push(`      targetPort: ${p.targetPort}`);
      lines.push(`      protocol: ${p.protocol}`);
    }
  }
  lines.push('');

  lines.push('resources:');
  lines.push('  requests:');
  lines.push(`    cpu: "${cfg.resourcesCpuRequest}"`);
  lines.push(`    memory: "${cfg.resourcesMemRequest}"`);
  lines.push('  limits:');
  lines.push(`    cpu: "${cfg.resourcesCpuLimit}"`);
  lines.push(`    memory: "${cfg.resourcesMemLimit}"`);
  lines.push('');

  lines.push('autoscaling:');
  lines.push(`  enabled: ${cfg.autoscalingEnabled}`);
  if (cfg.autoscalingEnabled) {
    lines.push(`  minReplicas: ${cfg.autoscalingMinReplicas}`);
    lines.push(`  maxReplicas: ${cfg.autoscalingMaxReplicas}`);
    lines.push(`  targetCPUUtilizationPercentage: ${cfg.autoscalingCpuUtilization}`);
  }
  lines.push('');

  lines.push('ingress:');
  lines.push(`  enabled: ${cfg.ingressEnabled}`);
  if (cfg.ingressEnabled) {
    lines.push(`  className: "${cfg.ingressClassName}"`);
    lines.push('  annotations: {}');
    lines.push('  hosts:');
    lines.push(`    - host: ${cfg.ingressHost}`);
    lines.push('      paths:');
    lines.push('        - path: /');
    lines.push('          pathType: Prefix');
    if (cfg.ingressTlsEnabled) {
      lines.push('  tls:');
      lines.push('    - secretName: tls-secret');
      lines.push(`      hosts:`);
      lines.push(`        - ${cfg.ingressHost}`);
    } else {
      lines.push('  tls: []');
    }
  }
  lines.push('');

  if (cfg.livenessEnabled || cfg.readinessEnabled) {
    lines.push('probes:');
    if (cfg.livenessEnabled) {
      lines.push('  liveness:');
      lines.push('    httpGet:');
      lines.push(`      path: ${cfg.livenessPath}`);
      lines.push(`      port: ${cfg.ports[0]?.targetPort ?? '8080'}`);
      lines.push('    initialDelaySeconds: 10');
      lines.push('    periodSeconds: 10');
    }
    if (cfg.readinessEnabled) {
      lines.push('  readiness:');
      lines.push('    httpGet:');
      lines.push(`      path: ${cfg.readinessPath}`);
      lines.push(`      port: ${cfg.ports[0]?.targetPort ?? '8080'}`);
      lines.push('    initialDelaySeconds: 5');
      lines.push('    periodSeconds: 10');
    }
    lines.push('');
  }

  if (cfg.envVars.length > 0) {
    lines.push('env:');
    for (const v of cfg.envVars) {
      lines.push(`  - name: ${v.name}`);
      lines.push(`    value: "${v.value}"`);
    }
    lines.push('');
  }

  lines.push('persistence:');
  lines.push(`  enabled: ${cfg.persistenceEnabled}`);
  if (cfg.persistenceEnabled) {
    lines.push(`  size: "${cfg.persistenceSize}"`);
    lines.push(`  storageClass: "${cfg.persistenceStorageClass}"`);
    lines.push('  accessMode: ReadWriteOnce');
  }
  lines.push('');

  lines.push('serviceAccount:');
  lines.push('  create: true');
  lines.push('  annotations: {}');
  lines.push('');

  lines.push('podAnnotations: {}');
  lines.push('podSecurityContext: {}');
  lines.push('securityContext: {}');
  lines.push('nodeSelector: {}');
  lines.push('tolerations: []');
  lines.push('affinity: {}');

  return lines.join('\n');
}

export default function HelmValuesGenerator() {
  const [preset, setPreset] = useState<ChartPreset>('nginx');
  const [cfg, setCfg] = useState<HelmConfig>({ ...DEFAULT_CONFIG, ...PRESETS.nginx });
  const [activeTab, setActiveTab] = useState<'image' | 'service' | 'resources' | 'ingress' | 'probes' | 'env' | 'persistence'>('image');
  const [copied, setCopied] = useState(false);

  const handlePreset = (p: ChartPreset) => {
    setPreset(p);
    setCfg({ ...DEFAULT_CONFIG, ...PRESETS[p] });
    setCopied(false);
  };

  const update = (key: keyof HelmConfig, val: HelmConfig[keyof HelmConfig]) => {
    setCfg((c) => ({ ...c, [key]: val }));
    setCopied(false);
  };

  const addPort = () => {
    update('ports', [...cfg.ports, { name: 'port', port: '3000', targetPort: '3000', protocol: 'TCP' }]);
  };
  const removePort = (i: number) => update('ports', cfg.ports.filter((_, idx) => idx !== i));
  const updatePort = (i: number, key: keyof ServicePort, val: string) => {
    const ports = cfg.ports.map((p, idx) => idx === i ? { ...p, [key]: val } : p);
    update('ports', ports);
  };

  const addEnv = () => update('envVars', [...cfg.envVars, { name: 'MY_VAR', value: 'value' }]);
  const removeEnv = (i: number) => update('envVars', cfg.envVars.filter((_, idx) => idx !== i));
  const updateEnv = (i: number, key: 'name' | 'value', val: string) => {
    update('envVars', cfg.envVars.map((e, idx) => idx === i ? { ...e, [key]: val } : e));
  };

  const output = generateValuesYaml(cfg);

  const handleCopy = () => {
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const TABS = [
    { key: 'image', label: 'Image' },
    { key: 'service', label: 'Service' },
    { key: 'resources', label: 'Resources' },
    { key: 'ingress', label: 'Ingress' },
    { key: 'probes', label: 'Probes' },
    { key: 'env', label: 'Env Vars' },
    { key: 'persistence', label: 'Persistence' },
  ] as const;

  return (
    <div class="space-y-6">
      {/* Preset buttons */}
      <div>
        <p class="text-sm text-text-muted mb-2 font-medium">Chart preset:</p>
        <div class="flex gap-2 flex-wrap">
          {(['nginx', 'postgres', 'redis', 'custom'] as ChartPreset[]).map((p) => (
            <button
              key={p}
              onClick={() => handlePreset(p)}
              class={`px-3 py-1.5 rounded-lg text-sm font-medium capitalize transition-colors ${
                preset === p
                  ? 'bg-brand-primary text-white'
                  : 'bg-surface-elevated text-text-muted hover:text-text-primary border border-border-default'
              }`}
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Form */}
        <div class="space-y-4">
          {/* Tab Nav */}
          <div class="flex gap-1 flex-wrap border-b border-border-default pb-2">
            {TABS.map((t) => (
              <button
                key={t.key}
                onClick={() => setActiveTab(t.key)}
                class={`px-3 py-1.5 rounded-t text-xs font-medium transition-colors ${
                  activeTab === t.key
                    ? 'bg-brand-primary text-white'
                    : 'text-text-muted hover:text-text-primary'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>

          {/* Tab: Image */}
          {activeTab === 'image' && (
            <div class="space-y-3">
              {[
                { label: 'Image Repository', key: 'imageRepository' as const, placeholder: 'nginx' },
                { label: 'Image Tag', key: 'imageTag' as const, placeholder: 'latest' },
                { label: 'Replica Count', key: 'replicaCount' as const, placeholder: '1' },
                { label: 'Namespace Override (optional)', key: 'namespaceOverride' as const, placeholder: 'production' },
              ].map(({ label, key, placeholder }) => (
                <div key={key}>
                  <label class="text-xs text-text-muted block mb-1">{label}</label>
                  <input
                    type="text"
                    class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary"
                    placeholder={placeholder}
                    value={String(cfg[key])}
                    onInput={(e) => update(key, (e.target as HTMLInputElement).value)}
                  />
                </div>
              ))}
              <div>
                <label class="text-xs text-text-muted block mb-1">Image Pull Policy</label>
                <select
                  class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary focus:outline-none focus:ring-1 focus:ring-brand-primary"
                  value={cfg.imagePullPolicy}
                  onChange={(e) => update('imagePullPolicy', (e.target as HTMLSelectElement).value as HelmConfig['imagePullPolicy'])}
                >
                  <option>IfNotPresent</option>
                  <option>Always</option>
                  <option>Never</option>
                </select>
              </div>
            </div>
          )}

          {/* Tab: Service */}
          {activeTab === 'service' && (
            <div class="space-y-3">
              <div>
                <label class="text-xs text-text-muted block mb-1">Service Type</label>
                <select
                  class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary focus:outline-none focus:ring-1 focus:ring-brand-primary"
                  value={cfg.serviceType}
                  onChange={(e) => update('serviceType', (e.target as HTMLSelectElement).value as HelmConfig['serviceType'])}
                >
                  <option>ClusterIP</option>
                  <option>NodePort</option>
                  <option>LoadBalancer</option>
                </select>
              </div>
              <div>
                <div class="flex items-center justify-between mb-2">
                  <label class="text-xs text-text-muted">Ports</label>
                  <button onClick={addPort} class="text-xs px-2 py-1 rounded bg-surface-elevated border border-border-default text-text-muted hover:text-text-primary">+ Add Port</button>
                </div>
                <div class="space-y-2">
                  {cfg.ports.map((p, i) => (
                    <div key={i} class="bg-background border border-border-default rounded p-2 space-y-2">
                      <div class="flex gap-2">
                        {(['name', 'port', 'targetPort'] as const).map((k) => (
                          <div key={k} class="flex-1">
                            <label class="text-xs text-text-muted block mb-0.5">{k}</label>
                            <input
                              type="text"
                              class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1 text-xs text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary"
                              value={p[k]}
                              onInput={(e) => updatePort(i, k, (e.target as HTMLInputElement).value)}
                            />
                          </div>
                        ))}
                        <button onClick={() => removePort(i)} class="text-red-400 hover:text-red-600 text-xs self-end pb-1">✕</button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Tab: Resources */}
          {activeTab === 'resources' && (
            <div class="space-y-3">
              <div class="grid grid-cols-2 gap-3">
                {[
                  { label: 'CPU Request', key: 'resourcesCpuRequest' as const, placeholder: '100m' },
                  { label: 'CPU Limit', key: 'resourcesCpuLimit' as const, placeholder: '500m' },
                  { label: 'Memory Request', key: 'resourcesMemRequest' as const, placeholder: '128Mi' },
                  { label: 'Memory Limit', key: 'resourcesMemLimit' as const, placeholder: '256Mi' },
                ].map(({ label, key, placeholder }) => (
                  <div key={key}>
                    <label class="text-xs text-text-muted block mb-1">{label}</label>
                    <input
                      type="text"
                      class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary"
                      placeholder={placeholder}
                      value={String(cfg[key])}
                      onInput={(e) => update(key, (e.target as HTMLInputElement).value)}
                    />
                  </div>
                ))}
              </div>
              <div class="border-t border-border-default pt-3">
                <label class="flex items-center gap-2 mb-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={cfg.autoscalingEnabled}
                    onChange={(e) => update('autoscalingEnabled', (e.target as HTMLInputElement).checked)}
                    class="w-4 h-4 accent-brand-primary"
                  />
                  <span class="text-sm text-text-muted">Enable Horizontal Pod Autoscaling (HPA)</span>
                </label>
                {cfg.autoscalingEnabled && (
                  <div class="grid grid-cols-3 gap-2">
                    {[
                      { label: 'Min Replicas', key: 'autoscalingMinReplicas' as const },
                      { label: 'Max Replicas', key: 'autoscalingMaxReplicas' as const },
                      { label: 'CPU % Target', key: 'autoscalingCpuUtilization' as const },
                    ].map(({ label, key }) => (
                      <div key={key}>
                        <label class="text-xs text-text-muted block mb-1">{label}</label>
                        <input
                          type="text"
                          class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary"
                          value={String(cfg[key])}
                          onInput={(e) => update(key, (e.target as HTMLInputElement).value)}
                        />
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Tab: Ingress */}
          {activeTab === 'ingress' && (
            <div class="space-y-3">
              <label class="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={cfg.ingressEnabled} onChange={(e) => update('ingressEnabled', (e.target as HTMLInputElement).checked)} class="w-4 h-4 accent-brand-primary" />
                <span class="text-sm text-text-muted">Enable Ingress</span>
              </label>
              {cfg.ingressEnabled && (
                <>
                  {[
                    { label: 'Ingress Class Name', key: 'ingressClassName' as const, placeholder: 'nginx' },
                    { label: 'Host', key: 'ingressHost' as const, placeholder: 'app.example.com' },
                  ].map(({ label, key, placeholder }) => (
                    <div key={key}>
                      <label class="text-xs text-text-muted block mb-1">{label}</label>
                      <input
                        type="text"
                        class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary"
                        placeholder={placeholder}
                        value={String(cfg[key])}
                        onInput={(e) => update(key, (e.target as HTMLInputElement).value)}
                      />
                    </div>
                  ))}
                  <label class="flex items-center gap-2 cursor-pointer">
                    <input type="checkbox" checked={cfg.ingressTlsEnabled} onChange={(e) => update('ingressTlsEnabled', (e.target as HTMLInputElement).checked)} class="w-4 h-4 accent-brand-primary" />
                    <span class="text-sm text-text-muted">Enable TLS</span>
                  </label>
                </>
              )}
            </div>
          )}

          {/* Tab: Probes */}
          {activeTab === 'probes' && (
            <div class="space-y-3">
              <label class="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={cfg.livenessEnabled} onChange={(e) => update('livenessEnabled', (e.target as HTMLInputElement).checked)} class="w-4 h-4 accent-brand-primary" />
                <span class="text-sm text-text-muted">Liveness Probe</span>
              </label>
              {cfg.livenessEnabled && (
                <div>
                  <label class="text-xs text-text-muted block mb-1">Liveness Path</label>
                  <input type="text" class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary" value={cfg.livenessPath} onInput={(e) => update('livenessPath', (e.target as HTMLInputElement).value)} />
                </div>
              )}
              <label class="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={cfg.readinessEnabled} onChange={(e) => update('readinessEnabled', (e.target as HTMLInputElement).checked)} class="w-4 h-4 accent-brand-primary" />
                <span class="text-sm text-text-muted">Readiness Probe</span>
              </label>
              {cfg.readinessEnabled && (
                <div>
                  <label class="text-xs text-text-muted block mb-1">Readiness Path</label>
                  <input type="text" class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary" value={cfg.readinessPath} onInput={(e) => update('readinessPath', (e.target as HTMLInputElement).value)} />
                </div>
              )}
            </div>
          )}

          {/* Tab: Env Vars */}
          {activeTab === 'env' && (
            <div class="space-y-3">
              <div class="flex items-center justify-between">
                <p class="text-sm font-medium text-text-muted">Environment Variables</p>
                <button onClick={addEnv} class="text-xs px-2 py-1 rounded bg-surface-elevated border border-border-default text-text-muted hover:text-text-primary">+ Add</button>
              </div>
              <div class="space-y-2">
                {cfg.envVars.map((v, i) => (
                  <div key={i} class="flex gap-2 items-center">
                    <input type="text" class="flex-1 bg-surface-elevated border border-border-default rounded px-2 py-1 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary" value={v.name} onInput={(e) => updateEnv(i, 'name', (e.target as HTMLInputElement).value)} placeholder="VAR_NAME" />
                    <span class="text-text-muted text-xs">=</span>
                    <input type="text" class="flex-1 bg-surface-elevated border border-border-default rounded px-2 py-1 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary" value={v.value} onInput={(e) => updateEnv(i, 'value', (e.target as HTMLInputElement).value)} placeholder="value" />
                    <button onClick={() => removeEnv(i)} class="text-red-400 hover:text-red-600 text-xs">✕</button>
                  </div>
                ))}
                {cfg.envVars.length === 0 && <p class="text-xs text-text-muted italic">No env vars configured.</p>}
              </div>
            </div>
          )}

          {/* Tab: Persistence */}
          {activeTab === 'persistence' && (
            <div class="space-y-3">
              <label class="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={cfg.persistenceEnabled} onChange={(e) => update('persistenceEnabled', (e.target as HTMLInputElement).checked)} class="w-4 h-4 accent-brand-primary" />
                <span class="text-sm text-text-muted">Enable Persistent Volume</span>
              </label>
              {cfg.persistenceEnabled && (
                <>
                  <div>
                    <label class="text-xs text-text-muted block mb-1">Volume Size</label>
                    <input type="text" class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary" value={cfg.persistenceSize} onInput={(e) => update('persistenceSize', (e.target as HTMLInputElement).value)} placeholder="5Gi" />
                  </div>
                  <div>
                    <label class="text-xs text-text-muted block mb-1">Storage Class</label>
                    <input type="text" class="w-full bg-surface-elevated border border-border-default rounded px-2 py-1.5 text-sm text-text-primary font-mono focus:outline-none focus:ring-1 focus:ring-brand-primary" value={cfg.persistenceStorageClass} onInput={(e) => update('persistenceStorageClass', (e.target as HTMLInputElement).value)} placeholder="standard" />
                  </div>
                </>
              )}
            </div>
          )}
        </div>

        {/* Right: Output */}
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <label class="text-sm font-medium text-text-muted">values.yaml</label>
            <button
              onClick={handleCopy}
              class={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                copied ? 'bg-green-500 text-white' : 'bg-brand-primary text-white hover:bg-brand-hover'
              }`}
            >
              {copied ? '✓ Copied' : 'Copy YAML'}
            </button>
          </div>
          <pre class="bg-surface-elevated border border-border-default rounded-lg p-4 text-xs text-text-primary overflow-auto font-mono whitespace-pre min-h-[400px] leading-5">
            {output}
          </pre>
          <p class="text-xs text-text-muted">
            Save as <code class="bg-surface-elevated px-1 rounded">values.yaml</code>. Deploy with <code class="bg-surface-elevated px-1 rounded">helm install my-release ./chart -f values.yaml</code>.
          </p>
        </div>
      </div>
    </div>
  );
}
