import { useState } from 'preact/hooks';

type TriggerType = 'event' | 'cron' | 'webhook';
type StepType = 'run' | 'sleep' | 'waitForEvent' | 'invoke' | 'sendEvent';
type Runtime = 'typescript' | 'python';

const STEP_LABELS: Record<StepType, string> = {
  run: 'step.run (execute code)',
  sleep: 'step.sleep (delay)',
  waitForEvent: 'step.waitForEvent (await event)',
  invoke: 'step.invoke (call function)',
  sendEvent: 'inngest.send (emit event)',
};

interface FunctionStep {
  id: string;
  type: StepType;
  name: string;
  description: string;
  timeout: string;
}

interface FunctionConfig {
  id: string;
  name: string;
  triggerType: TriggerType;
  eventName: string;
  cronSchedule: string;
  concurrencyLimit: number;
  retryCount: number;
  throttlePeriod: string;
  throttleCount: number;
  runtime: Runtime;
  cancelOnEvent: string;
}

function genId() {
  return Math.random().toString(36).slice(2, 8);
}

function generateCode(config: FunctionConfig, steps: FunctionStep[]): string {
  const fnId = config.id || 'my-function';
  const fnName = config.name || 'My Function';
  const { runtime } = config;

  const triggerBlock = config.triggerType === 'event'
    ? `event: { name: "${config.eventName || 'app/order.created'}" }`
    : config.triggerType === 'cron'
    ? `cron: "${config.cronSchedule || '0 9 * * *'}"`
    : `event: { name: "webhook/received" }`;

  const concurrencyBlock = config.concurrencyLimit > 0
    ? `  concurrency: { limit: ${config.concurrencyLimit} },\n` : '';
  const retryBlock = config.retryCount !== 3
    ? `  retries: ${config.retryCount},\n` : '';
  const throttleBlock = config.throttleCount > 0
    ? `  throttle: { period: "${config.throttlePeriod || '1m'}", count: ${config.throttleCount} },\n` : '';
  const cancelBlock = config.cancelOnEvent
    ? `  cancelOn: [{ event: "${config.cancelOnEvent}" }],\n` : '';

  if (runtime === 'typescript') {
    const stepCode = steps.map(s => {
      if (s.type === 'run') {
        return `  const result = await step.run("${s.name || 'process-data'}", async () => {
    // ${s.description || 'Your step logic here'}
    return { success: true };
  });`;
      }
      if (s.type === 'sleep') {
        return `  await step.sleep("${s.name || 'wait'}", "${s.timeout || '1h'}");`;
      }
      if (s.type === 'waitForEvent') {
        return `  const signal = await step.waitForEvent("${s.name || 'await-event'}", {
    event: "${s.description || 'app/event.received'}",
    timeout: "${s.timeout || '24h'}",
  });`;
      }
      if (s.type === 'invoke') {
        return `  const invoked = await step.invoke("${s.name || 'call-fn'}", {
    function: ${s.description || 'otherFunction'},
    data: { /* payload */ },
  });`;
      }
      if (s.type === 'sendEvent') {
        return `  await step.sendEvent("${s.name || 'send-event'}", {
    name: "${s.description || 'app/event.triggered'}",
    data: { /* payload */ },
  });`;
      }
      return '';
    }).join('\n\n');

    return `// ${fnName} — Generated by Inngest Function Builder
// https://devplaybook.cc/tools/inngest-function-builder

import { inngest } from "./client";

export const ${fnId.replace(/-/g, '_')} = inngest.createFunction(
  {
    id: "${fnId}",
    name: "${fnName}",
${concurrencyBlock}${retryBlock}${throttleBlock}${cancelBlock}  },
  { ${triggerBlock} },
  async ({ event, step }) => {
${stepCode || '    // Add steps above'}

    return { message: "Done" };
  }
);

// client.ts (if not already created)
// import { Inngest } from "inngest";
// export const inngest = new Inngest({ id: "my-app" });`;
  }

  if (runtime === 'python') {
    const stepCode = steps.map(s => {
      if (s.type === 'run') {
        return `    @inngest.create_function_step("${s.name || 'process-data'}")
    async def ${(s.name || 'process_data').replace(/-/g, '_')}(step):
        # ${s.description || 'Your step logic here'}
        return {"success": True}`;
      }
      if (s.type === 'sleep') {
        return `    await step.sleep("${s.name || 'wait'}", "${s.timeout || '1h'}")`;
      }
      if (s.type === 'waitForEvent') {
        return `    signal = await step.wait_for_event("${s.name || 'await-event'}", event="${s.description || 'app/event.received'}", timeout="${s.timeout || '24h'}")`;
      }
      if (s.type === 'sendEvent') {
        return `    await inngest.send(inngest.Event(name="${s.description || 'app/event.triggered'}", data={}))`;
      }
      return '';
    }).join('\n\n');

    return `# ${fnName} — Generated by Inngest Function Builder
# https://devplaybook.cc/tools/inngest-function-builder

import inngest

@inngest.create_function(
    fn_id="${fnId}",
    trigger=inngest.TriggerEvent(event="${config.eventName || 'app/order.created'}"),
    retries=${config.retryCount},
)
async def ${fnId.replace(/-/g, '_')}(ctx: inngest.Context, step: inngest.Step) -> dict:
    event = ctx.event

${stepCode || '    # Add steps above'}

    return {"message": "Done"}`;
  }

  return '';
}

export default function InngestFunctionBuilder() {
  const [config, setConfig] = useState<FunctionConfig>({
    id: 'process-order',
    name: 'Process Order',
    triggerType: 'event',
    eventName: 'app/order.created',
    cronSchedule: '0 9 * * *',
    concurrencyLimit: 10,
    retryCount: 3,
    throttlePeriod: '1m',
    throttleCount: 0,
    runtime: 'typescript',
    cancelOnEvent: '',
  });

  const [steps, setSteps] = useState<FunctionStep[]>([
    { id: genId(), type: 'run', name: 'validate-order', description: 'Validate order data and inventory', timeout: '' },
    { id: genId(), type: 'run', name: 'charge-payment', description: 'Process payment via Stripe', timeout: '' },
    { id: genId(), type: 'sleep', name: 'wait-fulfillment', description: '', timeout: '30m' },
    { id: genId(), type: 'sendEvent', name: 'notify-shipped', description: 'app/order.shipped', timeout: '' },
  ]);

  const [copied, setCopied] = useState(false);
  const [activeStep, setActiveStep] = useState<string | null>(null);

  function addStep(type: StepType) {
    setSteps(prev => [...prev, { id: genId(), type, name: '', description: '', timeout: '1h' }]);
  }

  function removeStep(id: string) {
    setSteps(prev => prev.filter(s => s.id !== id));
    if (activeStep === id) setActiveStep(null);
  }

  function updateStep(id: string, patch: Partial<FunctionStep>) {
    setSteps(prev => prev.map(s => s.id === id ? { ...s, ...patch } : s));
  }

  function moveStep(id: string, dir: -1 | 1) {
    setSteps(prev => {
      const idx = prev.findIndex(s => s.id === id);
      if (idx < 0) return prev;
      const next = [...prev];
      const swap = idx + dir;
      if (swap < 0 || swap >= next.length) return prev;
      [next[idx], next[swap]] = [next[swap], next[idx]];
      return next;
    });
  }

  const code = generateCode(config, steps);

  function copy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const active = steps.find(s => s.id === activeStep);
  const stepIcons: Record<StepType, string> = {
    run: '▶',
    sleep: '💤',
    waitForEvent: '⏳',
    invoke: '⚡',
    sendEvent: '📤',
  };

  return (
    <div class="space-y-6">
      {/* Config Panel */}
      <div class="bg-surface-2 border border-border rounded-xl p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        <div>
          <label class="block text-sm font-medium mb-1">Function ID</label>
          <input
            type="text"
            value={config.id}
            onInput={e => setConfig(c => ({ ...c, id: (e.target as HTMLInputElement).value }))}
            placeholder="my-function"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Function Name</label>
          <input
            type="text"
            value={config.name}
            onInput={e => setConfig(c => ({ ...c, name: (e.target as HTMLInputElement).value }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Runtime</label>
          <select
            value={config.runtime}
            onChange={e => setConfig(c => ({ ...c, runtime: (e.target as HTMLSelectElement).value as any }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          >
            <option value="typescript">TypeScript</option>
            <option value="python">Python</option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Trigger Type</label>
          <select
            value={config.triggerType}
            onChange={e => setConfig(c => ({ ...c, triggerType: (e.target as HTMLSelectElement).value as any }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          >
            <option value="event">Event</option>
            <option value="cron">Cron</option>
            <option value="webhook">Webhook</option>
          </select>
        </div>
        {config.triggerType === 'event' || config.triggerType === 'webhook' ? (
          <div>
            <label class="block text-sm font-medium mb-1">Event Name</label>
            <input
              type="text"
              value={config.eventName}
              onInput={e => setConfig(c => ({ ...c, eventName: (e.target as HTMLInputElement).value }))}
              placeholder="app/order.created"
              class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
            />
          </div>
        ) : (
          <div>
            <label class="block text-sm font-medium mb-1">Cron Schedule</label>
            <input
              type="text"
              value={config.cronSchedule}
              onInput={e => setConfig(c => ({ ...c, cronSchedule: (e.target as HTMLInputElement).value }))}
              placeholder="0 9 * * *"
              class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
            />
          </div>
        )}
        <div>
          <label class="block text-sm font-medium mb-1">Concurrency Limit</label>
          <input
            type="number"
            value={config.concurrencyLimit}
            onInput={e => setConfig(c => ({ ...c, concurrencyLimit: parseInt((e.target as HTMLInputElement).value) || 0 }))}
            min="0"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Retries</label>
          <input
            type="number"
            value={config.retryCount}
            onInput={e => setConfig(c => ({ ...c, retryCount: parseInt((e.target as HTMLInputElement).value) || 0 }))}
            min="0" max="20"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Cancel-on Event (optional)</label>
          <input
            type="text"
            value={config.cancelOnEvent}
            onInput={e => setConfig(c => ({ ...c, cancelOnEvent: (e.target as HTMLInputElement).value }))}
            placeholder="app/order.cancelled"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Steps */}
        <div>
          <h2 class="font-semibold text-sm uppercase tracking-wide text-text-muted mb-3">Steps ({steps.length})</h2>

          <div class="space-y-2 mb-4">
            {steps.map((step, i) => (
              <div
                key={step.id}
                onClick={() => setActiveStep(step.id === activeStep ? null : step.id)}
                class={`bg-surface-2 border rounded-lg p-3 cursor-pointer transition-colors ${activeStep === step.id ? 'border-accent' : 'border-border hover:border-accent/50'}`}
              >
                <div class="flex items-center gap-2">
                  <span class="text-sm">{stepIcons[step.type]}</span>
                  <span class="text-sm font-medium flex-1 truncate">{step.name || step.type}</span>
                  <span class="text-xs text-text-muted bg-surface px-2 py-0.5 rounded-full">{step.type}</span>
                  <div class="flex gap-1" onClick={e => e.stopPropagation()}>
                    <button onClick={() => moveStep(step.id, -1)} disabled={i === 0} class="text-xs px-1.5 py-0.5 rounded hover:bg-surface disabled:opacity-30">▲</button>
                    <button onClick={() => moveStep(step.id, 1)} disabled={i === steps.length - 1} class="text-xs px-1.5 py-0.5 rounded hover:bg-surface disabled:opacity-30">▼</button>
                    <button onClick={() => removeStep(step.id)} class="text-xs px-1.5 py-0.5 rounded hover:bg-red-500/20 text-red-400">✕</button>
                  </div>
                </div>
                {step.description && <p class="text-xs text-text-muted mt-1 pl-5">{step.description}</p>}
              </div>
            ))}
          </div>

          {active && (
            <div class="bg-surface-2 border border-accent/30 rounded-xl p-4 mb-4 space-y-3">
              <h3 class="text-sm font-semibold">Edit: {active.name || active.type}</h3>
              <div>
                <label class="block text-xs text-text-muted mb-1">Step Name / ID</label>
                <input
                  type="text"
                  value={active.name}
                  onInput={e => updateStep(active.id, { name: (e.target as HTMLInputElement).value })}
                  class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                />
              </div>
              <div>
                <label class="block text-xs text-text-muted mb-1">
                  {active.type === 'sendEvent' || active.type === 'waitForEvent' ? 'Event Name' :
                   active.type === 'invoke' ? 'Function Reference' : 'Description'}
                </label>
                <input
                  type="text"
                  value={active.description}
                  onInput={e => updateStep(active.id, { description: (e.target as HTMLInputElement).value })}
                  class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                />
              </div>
              {(active.type === 'sleep' || active.type === 'waitForEvent') && (
                <div>
                  <label class="block text-xs text-text-muted mb-1">Timeout</label>
                  <input
                    type="text"
                    value={active.timeout}
                    onInput={e => updateStep(active.id, { timeout: (e.target as HTMLInputElement).value })}
                    placeholder="30m / 1h / 24h"
                    class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                  />
                </div>
              )}
            </div>
          )}

          <div>
            <p class="text-xs text-text-muted mb-2">Add Step:</p>
            <div class="flex flex-wrap gap-2">
              {(Object.keys(STEP_LABELS) as StepType[]).map(type => (
                <button
                  key={type}
                  onClick={() => addStep(type)}
                  class="text-xs bg-surface border border-border rounded-lg px-2.5 py-1.5 hover:border-accent hover:text-accent transition-colors"
                >
                  {stepIcons[type]} {type}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Code Output */}
        <div>
          <div class="flex items-center justify-between mb-3">
            <h2 class="font-semibold text-sm uppercase tracking-wide text-text-muted">Generated Code</h2>
            <button
              onClick={copy}
              class="text-xs bg-accent text-white rounded-lg px-3 py-1.5 hover:bg-accent/90 transition-colors"
            >
              {copied ? '✓ Copied' : 'Copy Code'}
            </button>
          </div>
          <pre class="bg-surface border border-border rounded-xl p-4 text-xs font-mono overflow-x-auto overflow-y-auto max-h-[500px] whitespace-pre leading-relaxed text-text-muted">
            <code>{code}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
