import { useState } from 'preact/hooks';

type Stage = {
  duration: string;
  target: number;
};

type ThresholdEntry = {
  metric: string;
  condition: string;
};

export default function K6LoadTestGenerator() {
  const [scriptName, setScriptName] = useState('Load Test');
  const [baseUrl, setBaseUrl] = useState('https://api.example.com');
  const [endpoint, setEndpoint] = useState('/users');
  const [method, setMethod] = useState('GET');
  const [requestBody, setRequestBody] = useState('');
  const [stages, setStages] = useState<Stage[]>([
    { duration: '30s', target: 10 },
    { duration: '1m', target: 50 },
    { duration: '30s', target: 0 },
  ]);
  const [thresholds, setThresholds] = useState<ThresholdEntry[]>([
    { metric: 'http_req_duration', condition: "p(95)<500" },
    { metric: 'http_req_failed', condition: "rate<0.01" },
  ]);
  const [addAuthHeader, setAddAuthHeader] = useState(false);
  const [authToken, setAuthToken] = useState('YOUR_TOKEN_HERE');
  const [addContentType, setAddContentType] = useState(false);
  const [includeChecks, setIncludeChecks] = useState(true);
  const [copied, setCopied] = useState(false);

  const addStage = () => setStages(s => [...s, { duration: '1m', target: 10 }]);
  const removeStage = (i: number) => setStages(s => s.filter((_, idx) => idx !== i));
  const updateStage = (i: number, field: keyof Stage, value: string | number) => {
    setStages(s => s.map((st, idx) => idx === i ? { ...st, [field]: value } : st));
  };

  const addThreshold = () => setThresholds(t => [...t, { metric: 'http_req_duration', condition: 'p(95)<1000' }]);
  const removeThreshold = (i: number) => setThresholds(t => t.filter((_, idx) => idx !== i));
  const updateThreshold = (i: number, field: keyof ThresholdEntry, value: string) => {
    setThresholds(t => t.map((th, idx) => idx === i ? { ...th, [field]: value } : th));
  };

  const generateScript = () => {
    const stagesCode = stages.map(s => `    { duration: '${s.duration}', target: ${s.target} },`).join('\n');
    const thresholdLines = thresholds.map(t => `    '${t.metric}': ['${t.condition}'],`).join('\n');

    const headersLines: string[] = [];
    if (addContentType) headersLines.push("    'Content-Type': 'application/json',");
    if (addAuthHeader) headersLines.push(`    'Authorization': 'Bearer ${authToken}',`);
    const headersBlock = headersLines.length > 0
      ? `  const headers = {\n${headersLines.join('\n')}\n  };\n`
      : `  const headers = {};\n`;

    const bodyLine = (method === 'POST' || method === 'PUT' || method === 'PATCH') && requestBody.trim()
      ? `  const payload = JSON.stringify(${requestBody.trim()});\n`
      : '';

    const payloadArg = bodyLine ? ', payload' : (method !== 'GET' && method !== 'DELETE' ? ', null' : '');
    const paramsArg = headersLines.length > 0 ? `, { headers }` : '';

    const httpCall = method === 'GET'
      ? `  const res = http.get(\`\${BASE_URL}${endpoint}\`${paramsArg});`
      : method === 'DELETE'
      ? `  const res = http.del(\`\${BASE_URL}${endpoint}\`${paramsArg});`
      : `  const res = http.${method.toLowerCase()}(\`\${BASE_URL}${endpoint}\`${payloadArg}${paramsArg});`;

    const checksBlock = includeChecks
      ? `\n  check(res, {\n    'status is 200': (r) => r.status === 200,\n    'response time < 500ms': (r) => r.timings.duration < 500,\n  });\n`
      : '';

    return `import http from 'k6/http';
import { check, sleep } from 'k6';

// ${scriptName}
// Generated by DevPlaybook k6 Load Test Generator

const BASE_URL = '${baseUrl}';

export const options = {
  stages: [
${stagesCode}
  ],
  thresholds: {
${thresholdLines}
  },
};

export default function () {
${headersBlock}${bodyLine}${httpCall}
${checksBlock}
  sleep(1);
}
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateScript()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div class="space-y-6">
      {/* Basic Config */}
      <div class="bg-surface border border-border rounded-lg p-4 space-y-4">
        <h2 class="text-sm font-semibold text-text">Basic Configuration</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label class="text-xs text-text-muted mb-1 block">Script name</label>
            <input type="text" value={scriptName} onInput={e => setScriptName((e.target as HTMLInputElement).value)}
              class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-accent" />
          </div>
          <div>
            <label class="text-xs text-text-muted mb-1 block">Base URL</label>
            <input type="text" value={baseUrl} onInput={e => setBaseUrl((e.target as HTMLInputElement).value)}
              class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-accent font-mono" />
          </div>
          <div>
            <label class="text-xs text-text-muted mb-1 block">Endpoint path</label>
            <input type="text" value={endpoint} onInput={e => setEndpoint((e.target as HTMLInputElement).value)}
              class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-accent font-mono" />
          </div>
          <div>
            <label class="text-xs text-text-muted mb-1 block">HTTP method</label>
            <select value={method} onChange={e => setMethod((e.target as HTMLSelectElement).value)}
              class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-accent">
              {['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map(m => <option value={m}>{m}</option>)}
            </select>
          </div>
        </div>
        {(method === 'POST' || method === 'PUT' || method === 'PATCH') && (
          <div>
            <label class="text-xs text-text-muted mb-1 block">Request body (JSON object)</label>
            <textarea value={requestBody} onInput={e => setRequestBody((e.target as HTMLTextAreaElement).value)}
              rows={3}
              placeholder={'{ "name": "test", "value": 42 }'}
              class="w-full font-mono text-sm bg-background border border-border rounded px-3 py-1.5 resize-y focus:outline-none focus:ring-1 focus:ring-accent" />
          </div>
        )}
      </div>

      {/* Ramp Stages */}
      <div class="bg-surface border border-border rounded-lg p-4 space-y-3">
        <div class="flex items-center justify-between">
          <h2 class="text-sm font-semibold text-text">Ramp-up Stages</h2>
          <button onClick={addStage} class="text-xs px-2 py-1 bg-accent/10 text-accent border border-accent/30 rounded hover:bg-accent/20 transition-colors">+ Add stage</button>
        </div>
        {stages.map((stage, i) => (
          <div key={i} class="flex items-center gap-3">
            <div class="flex-1">
              <label class="text-xs text-text-muted mb-1 block">Duration</label>
              <input type="text" value={stage.duration} onInput={e => updateStage(i, 'duration', (e.target as HTMLInputElement).value)}
                placeholder="1m"
                class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 font-mono focus:outline-none focus:ring-1 focus:ring-accent" />
            </div>
            <div class="flex-1">
              <label class="text-xs text-text-muted mb-1 block">Target VUs</label>
              <input type="number" value={stage.target} onInput={e => updateStage(i, 'target', parseInt((e.target as HTMLInputElement).value) || 0)}
                min={0}
                class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-accent" />
            </div>
            {stages.length > 1 && (
              <button onClick={() => removeStage(i)} class="mt-5 text-xs px-2 py-1.5 bg-red-500/10 text-red-400 border border-red-500/20 rounded hover:bg-red-500/20 transition-colors">✕</button>
            )}
          </div>
        ))}
      </div>

      {/* Thresholds */}
      <div class="bg-surface border border-border rounded-lg p-4 space-y-3">
        <div class="flex items-center justify-between">
          <h2 class="text-sm font-semibold text-text">Thresholds (pass/fail criteria)</h2>
          <button onClick={addThreshold} class="text-xs px-2 py-1 bg-accent/10 text-accent border border-accent/30 rounded hover:bg-accent/20 transition-colors">+ Add threshold</button>
        </div>
        {thresholds.map((th, i) => (
          <div key={i} class="flex items-center gap-3">
            <div class="flex-1">
              <label class="text-xs text-text-muted mb-1 block">Metric</label>
              <select value={th.metric} onChange={e => updateThreshold(i, 'metric', (e.target as HTMLSelectElement).value)}
                class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-accent">
                <option value="http_req_duration">http_req_duration</option>
                <option value="http_req_failed">http_req_failed</option>
                <option value="http_reqs">http_reqs</option>
                <option value="vus">vus</option>
                <option value="iteration_duration">iteration_duration</option>
              </select>
            </div>
            <div class="flex-1">
              <label class="text-xs text-text-muted mb-1 block">Condition</label>
              <input type="text" value={th.condition} onInput={e => updateThreshold(i, 'condition', (e.target as HTMLInputElement).value)}
                placeholder="p(95)<500"
                class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 font-mono focus:outline-none focus:ring-1 focus:ring-accent" />
            </div>
            {thresholds.length > 1 && (
              <button onClick={() => removeThreshold(i)} class="mt-5 text-xs px-2 py-1.5 bg-red-500/10 text-red-400 border border-red-500/20 rounded hover:bg-red-500/20 transition-colors">✕</button>
            )}
          </div>
        ))}
      </div>

      {/* Options */}
      <div class="bg-surface border border-border rounded-lg p-4 space-y-3">
        <h2 class="text-sm font-semibold text-text">Options</h2>
        <label class="flex items-center gap-2 cursor-pointer">
          <input type="checkbox" checked={includeChecks} onChange={e => setIncludeChecks((e.target as HTMLInputElement).checked)}
            class="accent-accent" />
          <span class="text-sm text-text">Include response checks (status 200 + response time)</span>
        </label>
        <label class="flex items-center gap-2 cursor-pointer">
          <input type="checkbox" checked={addContentType} onChange={e => setAddContentType((e.target as HTMLInputElement).checked)}
            class="accent-accent" />
          <span class="text-sm text-text">Add Content-Type: application/json header</span>
        </label>
        <label class="flex items-center gap-2 cursor-pointer">
          <input type="checkbox" checked={addAuthHeader} onChange={e => setAddAuthHeader((e.target as HTMLInputElement).checked)}
            class="accent-accent" />
          <span class="text-sm text-text">Add Authorization: Bearer header</span>
        </label>
        {addAuthHeader && (
          <input type="text" value={authToken} onInput={e => setAuthToken((e.target as HTMLInputElement).value)}
            placeholder="YOUR_TOKEN_HERE"
            class="w-full text-sm bg-background border border-border rounded px-3 py-1.5 font-mono focus:outline-none focus:ring-1 focus:ring-accent ml-6" />
        )}
      </div>

      {/* Output */}
      <div>
        <div class="flex items-center justify-between mb-2">
          <label class="text-sm font-medium text-text-muted">Generated k6 script</label>
          <button onClick={handleCopy}
            class={`text-xs px-3 py-1.5 rounded border font-medium transition-colors ${copied ? 'bg-green-500/20 text-green-400 border-green-500/30' : 'bg-surface border-border hover:border-accent'}`}>
            {copied ? '✓ Copied!' : 'Copy script'}
          </button>
        </div>
        <pre class="w-full font-mono text-sm bg-background border border-border rounded-lg p-4 overflow-x-auto whitespace-pre text-text leading-relaxed">{generateScript()}</pre>
      </div>

      <div class="bg-surface border border-border rounded-lg p-4 text-xs text-text-muted">
        <p class="font-medium text-text mb-2">How to run</p>
        <ul class="space-y-1 list-disc list-inside">
          <li>Install k6: <code class="bg-background px-1 rounded">brew install k6</code> or <code class="bg-background px-1 rounded">choco install k6</code></li>
          <li>Save the script as <code class="bg-background px-1 rounded">load-test.js</code></li>
          <li>Run: <code class="bg-background px-1 rounded">k6 run load-test.js</code></li>
          <li>Output includes: VUs, RPS, response times, thresholds, and error rates</li>
        </ul>
      </div>
    </div>
  );
}
