import { useState } from 'preact/hooks';

type LbAlgorithm = 'round_robin' | 'least_conn' | 'ip_hash' | 'random' | 'weighted';
type LbEngine = 'nginx' | 'haproxy';

interface Backend {
  id: string;
  host: string;
  port: string;
  weight: number;
}

interface LbConfig {
  upstreamName: string;
  algorithm: LbAlgorithm;
  backends: Backend[];
  healthCheckEnabled: boolean;
  healthCheckPath: string;
  healthCheckInterval: number;
  connectTimeout: number;
  sendTimeout: number;
  readTimeout: number;
  sslTermination: boolean;
  domain: string;
  listenPort: number;
}

const ALGO_INFO: Record<LbAlgorithm, { label: string; hint: string }> = {
  round_robin: { label: 'Round Robin', hint: 'Distributes requests evenly in order. Default for nginx, HAProxy.' },
  least_conn: { label: 'Least Connections', hint: 'Routes to the backend with fewest active connections. Best for long-lived connections.' },
  ip_hash: { label: 'IP Hash', hint: 'Same client IP always goes to same backend (session affinity without cookies).' },
  random: { label: 'Random', hint: 'Picks a random backend. Simple, good baseline for stateless services.' },
  weighted: { label: 'Weighted', hint: 'Distribute traffic by weight. Use for canary deployments or mixed-capacity servers.' },
};

function uid() { return Math.random().toString(36).slice(2, 8); }

function genNginx(cfg: LbConfig): string {
  const algoLine = cfg.algorithm === 'least_conn' ? '\n    least_conn;'
    : cfg.algorithm === 'ip_hash' ? '\n    ip_hash;'
    : cfg.algorithm === 'random' ? '\n    random;'
    : '';

  const backends = cfg.backends.map(b => {
    const addr = `${b.host}:${b.port}`;
    const extra = cfg.algorithm === 'weighted' && b.weight !== 1 ? ` weight=${b.weight}` : '';
    const hc = cfg.healthCheckEnabled ? ' max_fails=3 fail_timeout=30s' : '';
    return `    server ${addr}${extra}${hc};`;
  }).join('\n');

  const healthCheck = cfg.healthCheckEnabled
    ? `\n    # Active health checks (requires nginx Plus or nginx_upstream_check_module)\n    # check interval=${cfg.healthCheckInterval}000 rise=2 fall=3 timeout=1000 type=http;\n    # check_http_send "GET ${cfg.healthCheckPath} HTTP/1.0\\r\\n\\r\\n";`
    : '';

  const upstreamBlock = `upstream ${cfg.upstreamName} {${algoLine}\n${backends}${healthCheck}\n\n    keepalive 32;\n}`;

  const sslBlock = cfg.sslTermination ? `
    # SSL termination
    listen 443 ssl;
    ssl_certificate /etc/ssl/certs/${cfg.domain}.crt;
    ssl_certificate_key /etc/ssl/private/${cfg.domain}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Redirect HTTP to HTTPS
    # server {
    #     listen 80;
    #     server_name ${cfg.domain};
    #     return 301 https://$host$request_uri;
    # }` : `
    listen ${cfg.listenPort};`;

  const serverBlock = `server {${sslBlock}
    server_name ${cfg.domain};

    # Timeouts
    proxy_connect_timeout ${cfg.connectTimeout}s;
    proxy_send_timeout    ${cfg.sendTimeout}s;
    proxy_read_timeout    ${cfg.readTimeout}s;

    location / {
        proxy_pass         http://${cfg.upstreamName};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;${cfg.healthCheckEnabled ? `

        # Passive health check
        proxy_next_upstream error timeout http_500 http_502 http_503;
        proxy_next_upstream_tries 3;` : ''}
    }
}`;

  return `# nginx Load Balancer Configuration
# Generated by DevPlaybook Load Balancer Config Generator
# Algorithm: ${ALGO_INFO[cfg.algorithm].label}

${upstreamBlock}

${serverBlock}`;
}

function genHaProxy(cfg: LbConfig): string {
  const algoMap: Record<LbAlgorithm, string> = {
    round_robin: 'roundrobin',
    least_conn: 'leastconn',
    ip_hash: 'source',
    random: 'random',
    weighted: 'roundrobin',
  };
  const algo = algoMap[cfg.algorithm];

  const servers = cfg.backends.map((b, i) => {
    const weight = cfg.algorithm === 'weighted' ? ` weight ${b.weight}` : '';
    const hc = cfg.healthCheckEnabled ? ` check inter ${cfg.healthCheckInterval}s rise 2 fall 3` : '';
    return `    server ${cfg.upstreamName}${i + 1} ${b.host}:${b.port}${weight}${hc}`;
  }).join('\n');

  const healthOpts = cfg.healthCheckEnabled
    ? `    option httpchk GET ${cfg.healthCheckPath}\n    http-check expect status 200\n` : '';

  const frontendBind = cfg.sslTermination
    ? `    bind *:443 ssl crt /etc/ssl/certs/${cfg.domain}.pem`
    : `    bind *:${cfg.listenPort}`;

  const sslRedirect = cfg.sslTermination
    ? `\nfrontend http_redirect
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }\n` : '';

  return `# HAProxy Load Balancer Configuration
# Generated by DevPlaybook Load Balancer Config Generator
# Algorithm: ${ALGO_INFO[cfg.algorithm].label}

global
    log /dev/log local0
    log /dev/log local1 notice
    daemon
    maxconn 50000

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect ${cfg.connectTimeout}s
    timeout client  ${cfg.sendTimeout}s
    timeout server  ${cfg.readTimeout}s
    option  forwardfor
    option  http-server-close
${sslRedirect}
frontend ${cfg.upstreamName}_frontend
${frontendBind}
    default_backend ${cfg.upstreamName}_backend

backend ${cfg.upstreamName}_backend
    balance ${algo}
${healthOpts}    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
${servers}`;
}

const DEFAULT_BACKENDS: Backend[] = [
  { id: uid(), host: '10.0.0.1', port: '8080', weight: 1 },
  { id: uid(), host: '10.0.0.2', port: '8080', weight: 1 },
  { id: uid(), host: '10.0.0.3', port: '8080', weight: 1 },
];

export default function LoadBalancerConfigGenerator() {
  const [engine, setEngine] = useState<LbEngine>('nginx');
  const [cfg, setCfg] = useState<LbConfig>({
    upstreamName: 'my_app',
    algorithm: 'round_robin',
    backends: DEFAULT_BACKENDS,
    healthCheckEnabled: true,
    healthCheckPath: '/health',
    healthCheckInterval: 10,
    connectTimeout: 5,
    sendTimeout: 60,
    readTimeout: 60,
    sslTermination: false,
    domain: 'example.com',
    listenPort: 80,
  });
  const [copied, setCopied] = useState(false);

  const output = engine === 'nginx' ? genNginx(cfg) : genHaProxy(cfg);

  function patch(p: Partial<LbConfig>) { setCfg(c => ({ ...c, ...p })); }

  function addBackend() {
    patch({ backends: [...cfg.backends, { id: uid(), host: '10.0.0.x', port: '8080', weight: 1 }] });
  }
  function removeBackend(id: string) {
    patch({ backends: cfg.backends.filter(b => b.id !== id) });
  }
  function updateBackend(id: string, key: keyof Backend, value: string | number) {
    patch({ backends: cfg.backends.map(b => b.id === id ? { ...b, [key]: value } : b) });
  }

  function handleCopy() {
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const inputClass = "w-full bg-bg-card border border-border rounded px-3 py-2 text-sm text-text-primary focus:outline-none focus:border-accent";
  const labelClass = "block text-xs font-medium text-text-muted mb-1 uppercase tracking-wide";
  const numClass = inputClass + " font-mono";

  return (
    <div class="space-y-5">
      {/* Engine Toggle */}
      <div class="flex gap-2">
        {(['nginx', 'haproxy'] as LbEngine[]).map(e => (
          <button
            key={e}
            onClick={() => setEngine(e)}
            class={`px-4 py-2 rounded font-medium text-sm border transition-colors ${
              engine === e ? 'bg-accent text-bg-base border-accent' : 'bg-bg-card text-text-muted border-border hover:border-accent'
            }`}
          >
            {e === 'nginx' ? 'nginx' : 'HAProxy'}
          </button>
        ))}
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {/* Upstream / Backend Name */}
        <div>
          <label class={labelClass}>Upstream Name</label>
          <input type="text" value={cfg.upstreamName} onInput={e => patch({ upstreamName: (e.target as HTMLInputElement).value })} class={inputClass} />
        </div>
        {/* Domain */}
        <div>
          <label class={labelClass}>Domain / server_name</label>
          <input type="text" value={cfg.domain} onInput={e => patch({ domain: (e.target as HTMLInputElement).value })} placeholder="example.com" class={inputClass} />
        </div>
      </div>

      {/* Algorithm */}
      <div>
        <label class={labelClass}>Load Balancing Algorithm</label>
        <div class="flex flex-wrap gap-2 mb-2">
          {(Object.keys(ALGO_INFO) as LbAlgorithm[]).map(a => (
            <button
              key={a}
              onClick={() => patch({ algorithm: a })}
              class={`px-3 py-1.5 rounded text-sm border transition-colors ${
                cfg.algorithm === a ? 'bg-accent text-bg-base border-accent' : 'bg-bg-card text-text-muted border-border hover:border-accent hover:text-text-primary'
              }`}
            >
              {ALGO_INFO[a].label}
            </button>
          ))}
        </div>
        <p class="text-xs text-text-muted">{ALGO_INFO[cfg.algorithm].hint}</p>
      </div>

      {/* Backend Servers */}
      <div>
        <div class="flex items-center justify-between mb-2">
          <label class={labelClass}>Backend Servers</label>
          <button
            onClick={addBackend}
            class="text-xs px-3 py-1 rounded bg-accent text-bg-base hover:opacity-90 transition-opacity"
          >
            + Add Server
          </button>
        </div>
        <div class="space-y-2">
          {cfg.backends.map(b => (
            <div key={b.id} class="flex gap-2 items-center">
              <input
                type="text"
                value={b.host}
                onInput={e => updateBackend(b.id, 'host', (e.target as HTMLInputElement).value)}
                placeholder="host / IP"
                class={inputClass + ' font-mono flex-1'}
              />
              <input
                type="text"
                value={b.port}
                onInput={e => updateBackend(b.id, 'port', (e.target as HTMLInputElement).value)}
                placeholder="port"
                class={numClass + ' w-20'}
              />
              {cfg.algorithm === 'weighted' && (
                <input
                  type="number"
                  min={1}
                  max={100}
                  value={b.weight}
                  onInput={e => updateBackend(b.id, 'weight', Number((e.target as HTMLInputElement).value))}
                  class={numClass + ' w-16'}
                  title="Weight"
                />
              )}
              <button
                onClick={() => removeBackend(b.id)}
                disabled={cfg.backends.length <= 1}
                class="text-text-muted hover:text-red-400 transition-colors px-1 disabled:opacity-30"
              >
                ✕
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Health Check */}
      <div>
        <div class="flex items-center gap-3 mb-3">
          <button
            onClick={() => patch({ healthCheckEnabled: !cfg.healthCheckEnabled })}
            class={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${cfg.healthCheckEnabled ? 'bg-accent' : 'bg-border'}`}
          >
            <span class={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${cfg.healthCheckEnabled ? 'translate-x-6' : 'translate-x-1'}`} />
          </button>
          <span class="text-sm text-text-primary font-medium">Health Checks</span>
        </div>
        {cfg.healthCheckEnabled && (
          <div class="grid grid-cols-2 sm:grid-cols-3 gap-3">
            <div class="col-span-2 sm:col-span-1">
              <label class={labelClass}>Check Path</label>
              <input type="text" value={cfg.healthCheckPath} onInput={e => patch({ healthCheckPath: (e.target as HTMLInputElement).value })} placeholder="/health" class={inputClass} />
            </div>
            <div>
              <label class={labelClass}>Interval (s)</label>
              <input type="number" min={1} value={cfg.healthCheckInterval} onInput={e => patch({ healthCheckInterval: Number((e.target as HTMLInputElement).value) })} class={numClass} />
            </div>
          </div>
        )}
      </div>

      {/* Timeouts */}
      <div>
        <label class={labelClass}>Timeouts (seconds)</label>
        <div class="grid grid-cols-3 gap-3">
          {(['connectTimeout', 'sendTimeout', 'readTimeout'] as const).map(k => (
            <div key={k}>
              <label class="block text-xs text-text-muted mb-1">{k.replace('Timeout', '').replace(/([A-Z])/g, ' $1')}</label>
              <input type="number" min={1} value={cfg[k]} onInput={e => patch({ [k]: Number((e.target as HTMLInputElement).value) } as Partial<LbConfig>)} class={numClass} />
            </div>
          ))}
        </div>
      </div>

      {/* SSL */}
      <div class="flex items-center gap-3">
        <button
          onClick={() => patch({ sslTermination: !cfg.sslTermination })}
          class={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${cfg.sslTermination ? 'bg-accent' : 'bg-border'}`}
        >
          <span class={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${cfg.sslTermination ? 'translate-x-6' : 'translate-x-1'}`} />
        </button>
        <span class="text-sm text-text-primary font-medium">SSL Termination</span>
        <span class="text-xs text-text-muted">(HTTPS at load balancer, HTTP to backends)</span>
      </div>

      {/* Output */}
      <div>
        <div class="flex items-center justify-between mb-2">
          <label class={labelClass}>Generated Config ({engine === 'nginx' ? 'nginx.conf' : 'haproxy.cfg'})</label>
          <button
            onClick={handleCopy}
            class="text-xs px-3 py-1 rounded bg-bg-card border border-border hover:border-accent text-text-muted hover:text-text-primary transition-colors"
          >
            {copied ? '✓ Copied!' : 'Copy'}
          </button>
        </div>
        <pre class="bg-bg-card border border-border rounded p-4 text-xs font-mono text-text-primary overflow-x-auto max-h-[32rem] overflow-y-auto whitespace-pre">{output}</pre>
      </div>
    </div>
  );
}
