import { useState, useCallback } from 'preact/hooks';

type CacheStrategy = 'cache-first' | 'network-first' | 'stale-while-revalidate';

interface SwConfig {
  cacheName: string;
  strategy: CacheStrategy;
  urlsToCache: string;
  offlineFallback: string;
  enableOfflineFallback: boolean;
  version: string;
}

const DEFAULT_CONFIG: SwConfig = {
  cacheName: 'my-app-cache',
  strategy: 'cache-first',
  urlsToCache: '/',
  offlineFallback: '/offline.html',
  enableOfflineFallback: false,
  version: 'v1',
};

const STRATEGY_INFO: Record<CacheStrategy, { label: string; desc: string; color: string }> = {
  'cache-first': {
    label: 'Cache First',
    desc: 'Serve from cache, fall back to network. Best for static assets.',
    color: 'text-green-400',
  },
  'network-first': {
    label: 'Network First',
    desc: 'Try network, fall back to cache. Best for dynamic content.',
    color: 'text-blue-400',
  },
  'stale-while-revalidate': {
    label: 'Stale While Revalidate',
    desc: 'Serve cache immediately, update in background. Best for balance.',
    color: 'text-yellow-400',
  },
};

function generateSW(cfg: SwConfig): string {
  const cacheName = `${cfg.cacheName}-${cfg.version}`;
  const urlList = cfg.urlsToCache
    .split('\n')
    .map((u) => u.trim())
    .filter(Boolean);
  const urlsJson = JSON.stringify(urlList, null, 2);

  const installHandler = `self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[SW] Pre-caching assets');
      return cache.addAll(URLS_TO_CACHE);
    })
  );
  self.skipWaiting();
});`;

  const activateHandler = `self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      )
    )
  );
  self.clients.claim();
});`;

  let fetchHandler = '';

  if (cfg.strategy === 'cache-first') {
    fetchHandler = `self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (!response || response.status !== 200 || response.type !== 'basic') {
          return response;
        }
        const cloned = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, cloned));
        return response;
      });
    })${cfg.enableOfflineFallback ? `.catch(() => caches.match('${cfg.offlineFallback}'))` : ''}
  );
});`;
  } else if (cfg.strategy === 'network-first') {
    fetchHandler = `self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    fetch(event.request)
      .then((response) => {
        if (!response || response.status !== 200 || response.type !== 'basic') {
          return response;
        }
        const cloned = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, cloned));
        return response;
      })
      .catch(() =>
        caches.match(event.request)${cfg.enableOfflineFallback ? `\n          .then((cached) => cached || caches.match('${cfg.offlineFallback}'))` : ''}
      )
  );
});`;
  } else {
    // stale-while-revalidate
    fetchHandler = `self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.open(CACHE_NAME).then((cache) =>
      cache.match(event.request).then((cached) => {
        const networkFetch = fetch(event.request).then((response) => {
          if (response && response.status === 200 && response.type === 'basic') {
            cache.put(event.request, response.clone());
          }
          return response;
        })${cfg.enableOfflineFallback ? `.catch(() => caches.match('${cfg.offlineFallback}'))` : ''};
        return cached || networkFetch;
      })
    )
  );
});`;
  }

  return `// Service Worker — ${STRATEGY_INFO[cfg.strategy].label} Strategy
// Generated by DevPlaybook PWA Tools

const CACHE_NAME = '${cacheName}';
const URLS_TO_CACHE = ${urlsJson};

${installHandler}

${activateHandler}

${fetchHandler}`;
}

function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/javascript' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ServiceWorkerGenerator() {
  const [cfg, setCfg] = useState<SwConfig>(DEFAULT_CONFIG);
  const [copied, setCopied] = useState(false);

  const update = useCallback(<K extends keyof SwConfig>(key: K, val: SwConfig[K]) => {
    setCfg((prev) => ({ ...prev, [key]: val }));
  }, []);

  const swCode = generateSW(cfg);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(swCode).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Left: Config */}
      <div class="space-y-5">
        {/* Strategy picker */}
        <div>
          <label class="block text-sm font-medium text-text-muted mb-2">Cache Strategy</label>
          <div class="space-y-2">
            {(Object.entries(STRATEGY_INFO) as [CacheStrategy, typeof STRATEGY_INFO[CacheStrategy]][]).map(([key, info]) => (
              <button
                key={key}
                onClick={() => update('strategy', key)}
                class={`w-full text-left px-4 py-3 rounded-xl border transition-colors ${
                  cfg.strategy === key
                    ? 'bg-primary/10 border-primary'
                    : 'bg-surface border-border hover:border-primary/40'
                }`}
              >
                <div class={`text-sm font-medium ${info.color}`}>{info.label}</div>
                <div class="text-xs text-text-muted mt-0.5">{info.desc}</div>
              </button>
            ))}
          </div>
        </div>

        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium text-text-muted mb-1">Cache Name</label>
            <input
              type="text"
              value={cfg.cacheName}
              onInput={(e) => update('cacheName', (e.target as HTMLInputElement).value)}
              class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm font-mono text-text focus:outline-none focus:border-primary"
              placeholder="my-app-cache"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-text-muted mb-1">Version</label>
            <input
              type="text"
              value={cfg.version}
              onInput={(e) => update('version', (e.target as HTMLInputElement).value)}
              class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm font-mono text-text focus:outline-none focus:border-primary"
              placeholder="v1"
            />
          </div>
        </div>

        <div>
          <label class="block text-sm font-medium text-text-muted mb-1">URLs to Cache <span class="text-xs opacity-60">(one per line)</span></label>
          <textarea
            value={cfg.urlsToCache}
            onInput={(e) => update('urlsToCache', (e.target as HTMLTextAreaElement).value)}
            rows={5}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm font-mono text-text focus:outline-none focus:border-primary resize-none"
            placeholder={`/\n/index.html\n/styles.css\n/app.js\n/offline.html`}
          />
        </div>

        <div>
          <label class="flex items-center gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={cfg.enableOfflineFallback}
              onChange={(e) => update('enableOfflineFallback', (e.target as HTMLInputElement).checked)}
              class="w-4 h-4 rounded border-border accent-primary"
            />
            <span class="text-sm font-medium text-text">Enable offline fallback page</span>
          </label>
          {cfg.enableOfflineFallback && (
            <div class="mt-2">
              <input
                type="text"
                value={cfg.offlineFallback}
                onInput={(e) => update('offlineFallback', (e.target as HTMLInputElement).value)}
                class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm font-mono text-text focus:outline-none focus:border-primary"
                placeholder="/offline.html"
              />
            </div>
          )}
        </div>

        {/* Registration snippet */}
        <div>
          <p class="text-xs text-text-muted mb-2">Register in your main JS:</p>
          <pre class="bg-surface rounded-lg border border-border p-3 text-xs font-mono text-green-400 overflow-x-auto">
{`if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js')
      .then((reg) => console.log('SW registered', reg))
      .catch((err) => console.error('SW error', err));
  });
}`}
          </pre>
        </div>
      </div>

      {/* Right: Generated code */}
      <div class="flex flex-col gap-4">
        <div class="flex items-center justify-between">
          <span class="text-sm font-medium text-text-muted">sw.js</span>
          <div class="flex gap-2">
            <button
              onClick={copyToClipboard}
              class="px-3 py-1.5 rounded-lg text-xs bg-surface border border-border text-text-muted hover:text-text hover:border-primary/50 transition-colors"
            >
              {copied ? '✓ Copied' : 'Copy'}
            </button>
            <button
              onClick={() => downloadFile(swCode, 'sw.js')}
              class="px-3 py-1.5 rounded-lg text-xs bg-primary text-white hover:bg-primary/90 transition-colors"
            >
              Download sw.js
            </button>
          </div>
        </div>
        <pre class="flex-1 bg-surface rounded-xl border border-border p-4 text-xs font-mono text-text overflow-auto leading-relaxed whitespace-pre min-h-96">
          {swCode}
        </pre>
      </div>
    </div>
  );
}
