import { useState, useCallback } from 'preact/hooks';

type CacheStrategy = 'network-first' | 'cache-first' | 'stale-while-revalidate' | 'cache-only' | 'network-only';
type AgeUnit = 'seconds' | 'minutes' | 'hours' | 'days';

interface RouteRule {
  id: string;
  pattern: string;
  strategy: CacheStrategy;
  cacheName: string;
  maxAge: string;
  maxAgeUnit: AgeUnit;
  maxEntries: string;
}

interface GeneralSettings {
  swVersion: string;
  precacheUrls: string;
  offlineFallbackUrl: string;
}

const STRATEGIES: { value: CacheStrategy; label: string; color: string; badge: string; description: string; detail: string }[] = [
  {
    value: 'network-first',
    label: 'Network First',
    color: 'text-blue-400',
    badge: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
    description: 'Fresh data, falls back to cache',
    detail: 'Tries the network first. If the network fails or is slow, serves from cache. Best for HTML pages and API responses where freshness matters.',
  },
  {
    value: 'cache-first',
    label: 'Cache First',
    color: 'text-green-400',
    badge: 'bg-green-500/20 text-green-400 border-green-500/30',
    description: 'Speed, falls back to network',
    detail: 'Serves from cache immediately if available, otherwise fetches from network and caches the result. Best for static assets like images, fonts, CSS.',
  },
  {
    value: 'stale-while-revalidate',
    label: 'Stale While Revalidate',
    color: 'text-purple-400',
    badge: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
    description: 'Instant response, updates in background',
    detail: 'Responds from cache immediately, then fetches a fresh copy in the background for next time. Best for non-critical resources that should stay relatively fresh.',
  },
  {
    value: 'cache-only',
    label: 'Cache Only',
    color: 'text-orange-400',
    badge: 'bg-orange-500/20 text-orange-400 border-orange-500/30',
    description: 'Offline-only resources',
    detail: 'Only serves from cache, never hits the network. Best for resources precached during install that should never change.',
  },
  {
    value: 'network-only',
    label: 'Network Only',
    color: 'text-gray-400',
    badge: 'bg-gray-500/20 text-gray-400 border-gray-500/30',
    description: 'Always fresh, no caching',
    detail: 'Always fetches from the network, never uses cache. Best for analytics, POST requests, or anything that must always be fresh.',
  },
];

function deriveCacheName(pattern: string): string {
  return pattern
    .replace(/[^a-z0-9]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase() || 'default-cache';
}

function toSeconds(value: string, unit: AgeUnit): number {
  const n = parseInt(value, 10);
  if (isNaN(n) || n <= 0) return 0;
  switch (unit) {
    case 'seconds': return n;
    case 'minutes': return n * 60;
    case 'hours': return n * 3600;
    case 'days': return n * 86400;
  }
}

function generateSW(settings: GeneralSettings, rules: RouteRule[]): string {
  const precacheList = settings.precacheUrls
    .split('\n')
    .map((u) => u.trim())
    .filter(Boolean);

  const cacheNames = Array.from(new Set(rules.map((r) => r.cacheName || deriveCacheName(r.pattern))));

  const lines: string[] = [];

  lines.push(`// Service Worker — generated by DevPlaybook SW Cache Strategy Generator`);
  lines.push(`// Version: ${settings.swVersion || 'v1.0.0'}`);
  lines.push(``);
  lines.push(`const CACHE_VERSION = '${settings.swVersion || 'v1.0.0'}';`);
  lines.push(`const PRECACHE_NAME = \`precache-\${CACHE_VERSION}\`;`);
  lines.push(``);
  lines.push(`const PRECACHE_URLS = [`);
  if (precacheList.length > 0) {
    precacheList.forEach((url) => lines.push(`  '${url}',`));
  } else {
    lines.push(`  // Add URLs to precache here`);
  }
  lines.push(`];`);
  lines.push(``);

  const allCacheNames = ['PRECACHE_NAME', ...cacheNames.map((n) => `\`${n}-\${CACHE_VERSION}\``)];
  lines.push(`const ALL_CACHE_NAMES = [PRECACHE_NAME, ${cacheNames.map((n) => `\`${n}-\${CACHE_VERSION}\``).join(', ')}];`);
  lines.push(``);

  // Expiration helper
  lines.push(`// --- Expiration helpers (no Workbox dependency) ---`);
  lines.push(``);
  lines.push(`async function enforceExpiration(cacheName, maxEntries, maxAgeSeconds) {`);
  lines.push(`  const cache = await caches.open(cacheName);`);
  lines.push(`  const keys = await cache.keys();`);
  lines.push(`  const now = Date.now();`);
  lines.push(`  const meta = await getExpMeta(cacheName);`);
  lines.push(``);
  lines.push(`  // Remove expired entries`);
  lines.push(`  if (maxAgeSeconds > 0) {`);
  lines.push(`    for (const request of keys) {`);
  lines.push(`      const ts = meta[request.url];`);
  lines.push(`      if (ts && now - ts > maxAgeSeconds * 1000) {`);
  lines.push(`        await cache.delete(request);`);
  lines.push(`        delete meta[request.url];`);
  lines.push(`      }`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  // Enforce max entries (remove oldest first)`);
  lines.push(`  if (maxEntries > 0) {`);
  lines.push(`    const remaining = await cache.keys();`);
  lines.push(`    if (remaining.length > maxEntries) {`);
  lines.push(`      const sorted = remaining.sort((a, b) => (meta[a.url] || 0) - (meta[b.url] || 0));`);
  lines.push(`      const toDelete = sorted.slice(0, remaining.length - maxEntries);`);
  lines.push(`      for (const req of toDelete) {`);
  lines.push(`        await cache.delete(req);`);
  lines.push(`        delete meta[req.url];`);
  lines.push(`      }`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  await setExpMeta(cacheName, meta);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`const EXP_META_CACHE = 'sw-exp-meta';`);
  lines.push(``);
  lines.push(`async function getExpMeta(cacheName) {`);
  lines.push(`  try {`);
  lines.push(`    const c = await caches.open(EXP_META_CACHE);`);
  lines.push(`    const res = await c.match(cacheName);`);
  lines.push(`    if (!res) return {};`);
  lines.push(`    return await res.json();`);
  lines.push(`  } catch { return {}; }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function setExpMeta(cacheName, meta) {`);
  lines.push(`  const c = await caches.open(EXP_META_CACHE);`);
  lines.push(`  await c.put(cacheName, new Response(JSON.stringify(meta), { headers: { 'Content-Type': 'application/json' } }));`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function recordCacheTimestamp(cacheName, url) {`);
  lines.push(`  const meta = await getExpMeta(cacheName);`);
  lines.push(`  meta[url] = Date.now();`);
  lines.push(`  await setExpMeta(cacheName, meta);`);
  lines.push(`}`);
  lines.push(``);

  // Pattern matching helper
  lines.push(`// --- Route pattern matching ---`);
  lines.push(``);
  lines.push(`function matchesPattern(url, pattern) {`);
  lines.push(`  const path = new URL(url).pathname;`);
  lines.push(`  if (pattern.startsWith('/') || pattern.startsWith('*')) {`);
  lines.push("    const re = pattern.replace(/[-\\.+?^${}()|[\\]\\\\]/g, '\\\\$&').replace(/\\*/g, '.*');");
  lines.push("    const regex = new RegExp('^' + re + '$');");
  lines.push(`    return regex.test(path);`);
  lines.push(`  }`);
  lines.push(`  // Extension pattern like *.css`);
  lines.push(`  if (pattern.startsWith('*.')) {`);
  lines.push(`    return path.endsWith(pattern.slice(1));`);
  lines.push(`  }`);
  lines.push(`  return path.includes(pattern);`);
  lines.push(`}`);
  lines.push(``);

  // Strategy functions
  lines.push(`// --- Strategy implementations ---`);
  lines.push(``);

  lines.push(`async function networkFirst(request, cacheName, maxEntries, maxAgeSeconds) {`);
  lines.push(`  try {`);
  lines.push(`    const response = await fetch(request);`);
  lines.push(`    const cache = await caches.open(cacheName);`);
  lines.push(`    await cache.put(request, response.clone());`);
  lines.push(`    await recordCacheTimestamp(cacheName, request.url);`);
  lines.push(`    await enforceExpiration(cacheName, maxEntries, maxAgeSeconds);`);
  lines.push(`    return response;`);
  lines.push(`  } catch {`);
  lines.push(`    const cached = await caches.match(request);`);
  if (settings.offlineFallbackUrl) {
    lines.push(`    return cached || caches.match('${settings.offlineFallbackUrl}');`);
  } else {
    lines.push(`    return cached || new Response('Network error', { status: 503 });`);
  }
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  lines.push(`async function cacheFirst(request, cacheName, maxEntries, maxAgeSeconds) {`);
  lines.push(`  const cached = await caches.match(request);`);
  lines.push(`  if (cached) return cached;`);
  lines.push(`  try {`);
  lines.push(`    const response = await fetch(request);`);
  lines.push(`    const cache = await caches.open(cacheName);`);
  lines.push(`    await cache.put(request, response.clone());`);
  lines.push(`    await recordCacheTimestamp(cacheName, request.url);`);
  lines.push(`    await enforceExpiration(cacheName, maxEntries, maxAgeSeconds);`);
  lines.push(`    return response;`);
  lines.push(`  } catch {`);
  if (settings.offlineFallbackUrl) {
    lines.push(`    return caches.match('${settings.offlineFallbackUrl}');`);
  } else {
    lines.push(`    return new Response('Network error', { status: 503 });`);
  }
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  lines.push(`async function staleWhileRevalidate(request, cacheName, maxEntries, maxAgeSeconds) {`);
  lines.push(`  const cached = await caches.match(request);`);
  lines.push(`  const fetchPromise = fetch(request).then(async (response) => {`);
  lines.push(`    const cache = await caches.open(cacheName);`);
  lines.push(`    await cache.put(request, response.clone());`);
  lines.push(`    await recordCacheTimestamp(cacheName, request.url);`);
  lines.push(`    await enforceExpiration(cacheName, maxEntries, maxAgeSeconds);`);
  lines.push(`    return response;`);
  lines.push(`  });`);
  lines.push(`  return cached || fetchPromise;`);
  lines.push(`}`);
  lines.push(``);

  lines.push(`async function cacheOnly(request) {`);
  lines.push(`  const cached = await caches.match(request);`);
  if (settings.offlineFallbackUrl) {
    lines.push(`  return cached || caches.match('${settings.offlineFallbackUrl}');`);
  } else {
    lines.push(`  return cached || new Response('Not in cache', { status: 503 });`);
  }
  lines.push(`}`);
  lines.push(``);

  lines.push(`async function networkOnly(request) {`);
  lines.push(`  return fetch(request);`);
  lines.push(`}`);
  lines.push(``);

  // Install event
  lines.push(`// --- Install event ---`);
  lines.push(``);
  lines.push(`self.addEventListener('install', (event) => {`);
  lines.push(`  event.waitUntil(`);
  lines.push(`    caches.open(PRECACHE_NAME).then((cache) => {`);
  lines.push(`      return cache.addAll(PRECACHE_URLS);`);
  lines.push(`    }).then(() => self.skipWaiting())`);
  lines.push(`  );`);
  lines.push(`});`);
  lines.push(``);

  // Activate event
  lines.push(`// --- Activate event ---`);
  lines.push(``);
  lines.push(`self.addEventListener('activate', (event) => {`);
  lines.push(`  event.waitUntil(`);
  lines.push(`    caches.keys().then((keys) => {`);
  lines.push(`      return Promise.all(`);
  lines.push(`        keys`);
  lines.push(`          .filter((key) => !ALL_CACHE_NAMES.includes(key) && key !== EXP_META_CACHE)`);
  lines.push(`          .map((key) => caches.delete(key))`);
  lines.push(`      );`);
  lines.push(`    }).then(() => self.clients.claim())`);
  lines.push(`  );`);
  lines.push(`});`);
  lines.push(``);

  // Fetch event
  lines.push(`// --- Fetch event ---`);
  lines.push(``);
  lines.push(`self.addEventListener('fetch', (event) => {`);
  lines.push(`  const { request } = event;`);
  lines.push(`  if (request.method !== 'GET') return;`);
  lines.push(``);

  rules.forEach((rule, idx) => {
    const cacheName = rule.cacheName || deriveCacheName(rule.pattern);
    const maxAgeSec = toSeconds(rule.maxAge, rule.maxAgeUnit);
    const maxEntries = parseInt(rule.maxEntries, 10) || 0;
    const fullCacheName = `\`${cacheName}-\${CACHE_VERSION}\``;

    lines.push(`  // Rule ${idx + 1}: ${rule.pattern} — ${rule.strategy}`);
    lines.push(`  if (matchesPattern(request.url, '${rule.pattern}')) {`);

    switch (rule.strategy) {
      case 'network-first':
        lines.push(`    event.respondWith(networkFirst(request, ${fullCacheName}, ${maxEntries}, ${maxAgeSec}));`);
        break;
      case 'cache-first':
        lines.push(`    event.respondWith(cacheFirst(request, ${fullCacheName}, ${maxEntries}, ${maxAgeSec}));`);
        break;
      case 'stale-while-revalidate':
        lines.push(`    event.respondWith(staleWhileRevalidate(request, ${fullCacheName}, ${maxEntries}, ${maxAgeSec}));`);
        break;
      case 'cache-only':
        lines.push(`    event.respondWith(cacheOnly(request));`);
        break;
      case 'network-only':
        lines.push(`    event.respondWith(networkOnly(request));`);
        break;
    }

    lines.push(`    return;`);
    lines.push(`  }`);
    lines.push(``);
  });

  lines.push(`  // Default: network first for unmatched routes`);
  lines.push(`  event.respondWith(networkFirst(request, \`default-\${CACHE_VERSION}\`, 50, 0));`);
  lines.push(`});`);

  return lines.join('\n');
}

function StrategyBadge({ strategy }: { strategy: CacheStrategy }) {
  const s = STRATEGIES.find((x) => x.value === strategy)!;
  return (
    <span class={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium border ${s.badge}`}>
      {s.label}
    </span>
  );
}

function StrategyInfoCard({ strategy }: { strategy: CacheStrategy | null }) {
  if (!strategy) return null;
  const s = STRATEGIES.find((x) => x.value === strategy);
  if (!s) return null;
  return (
    <div class="mt-1 p-2 rounded-lg bg-background border border-border text-xs text-text-muted leading-relaxed">
      <span class={`font-semibold ${s.color}`}>{s.label}</span>: {s.detail}
    </div>
  );
}

let idCounter = 0;
function uid() {
  return `rule-${++idCounter}-${Math.random().toString(36).slice(2, 7)}`;
}

const DEFAULT_RULES: RouteRule[] = [
  { id: uid(), pattern: '/api/*', strategy: 'network-first', cacheName: 'api-cache', maxAge: '5', maxAgeUnit: 'minutes', maxEntries: '50' },
  { id: uid(), pattern: '*.js', strategy: 'cache-first', cacheName: 'js-cache', maxAge: '7', maxAgeUnit: 'days', maxEntries: '100' },
  { id: uid(), pattern: '*.css', strategy: 'cache-first', cacheName: 'css-cache', maxAge: '7', maxAgeUnit: 'days', maxEntries: '50' },
  { id: uid(), pattern: '/images/*', strategy: 'stale-while-revalidate', cacheName: 'images-cache', maxAge: '30', maxAgeUnit: 'days', maxEntries: '200' },
];

export default function ServiceWorkerCacheStrategyGenerator() {
  const [rules, setRules] = useState<RouteRule[]>(DEFAULT_RULES);
  const [settings, setSettings] = useState<GeneralSettings>({
    swVersion: 'v1.0.0',
    precacheUrls: '/',
    offlineFallbackUrl: '/offline.html',
  });
  const [hoveredStrategy, setHoveredStrategy] = useState<CacheStrategy | null>(null);
  const [activeInfoRule, setActiveInfoRule] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const generated = generateSW(settings, rules);

  const addRule = useCallback(() => {
    setRules((prev) => [
      ...prev,
      { id: uid(), pattern: '/new-route/*', strategy: 'network-first', cacheName: '', maxAge: '', maxAgeUnit: 'seconds', maxEntries: '' },
    ]);
  }, []);

  const removeRule = useCallback((id: string) => {
    setRules((prev) => prev.filter((r) => r.id !== id));
  }, []);

  const updateRule = useCallback((id: string, field: keyof RouteRule, value: string) => {
    setRules((prev) =>
      prev.map((r) => {
        if (r.id !== id) return r;
        const updated = { ...r, [field]: value };
        if (field === 'pattern' && !r.cacheName) {
          updated.cacheName = deriveCacheName(value);
        }
        return updated;
      })
    );
  }, []);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(generated);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback
    }
  }, [generated]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([generated], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sw.js';
    a.click();
    URL.revokeObjectURL(url);
  }, [generated]);

  const inputClass = 'w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm font-mono text-text focus:outline-none focus:border-primary';
  const smallInputClass = 'bg-surface border border-border rounded-lg px-2 py-1.5 text-xs font-mono text-text focus:outline-none focus:border-primary';

  return (
    <div class="w-full space-y-4 font-sans">
      {/* Strategy Legend */}
      <div class="bg-background border border-border rounded-xl p-4">
        <p class="text-xs text-text-muted mb-2 font-medium uppercase tracking-wide">Cache Strategies</p>
        <div class="flex flex-wrap gap-2">
          {STRATEGIES.map((s) => (
            <button
              key={s.value}
              class={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg border text-xs font-medium transition-all cursor-default ${s.badge}`}
              onMouseEnter={() => setHoveredStrategy(s.value)}
              onMouseLeave={() => setHoveredStrategy(null)}
            >
              {s.label}
              <span class="opacity-60">— {s.description}</span>
            </button>
          ))}
        </div>
        {hoveredStrategy && (
          <div class="mt-2 p-2 rounded-lg bg-surface border border-border text-xs text-text-muted leading-relaxed">
            {STRATEGIES.find((s) => s.value === hoveredStrategy)?.detail}
          </div>
        )}
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* LEFT PANEL */}
        <div class="space-y-4">
          {/* General Settings */}
          <div class="bg-background border border-border rounded-xl p-6 space-y-4">
            <h3 class="text-sm font-semibold text-text">General Settings</h3>

            <div>
              <label class="block text-xs text-text-muted mb-1">SW Version</label>
              <input
                type="text"
                class={inputClass}
                value={settings.swVersion}
                onInput={(e) => setSettings((s) => ({ ...s, swVersion: (e.target as HTMLInputElement).value }))}
                placeholder="v1.0.0"
              />
            </div>

            <div>
              <label class="block text-xs text-text-muted mb-1">Precache URLs <span class="opacity-50">(one per line)</span></label>
              <textarea
                class={`${inputClass} resize-y min-h-[72px]`}
                value={settings.precacheUrls}
                onInput={(e) => setSettings((s) => ({ ...s, precacheUrls: (e.target as HTMLTextAreaElement).value }))}
                placeholder={`/\n/index.html\n/offline.html`}
                rows={3}
              />
            </div>

            <div>
              <label class="block text-xs text-text-muted mb-1">Offline Fallback URL <span class="opacity-50">(optional)</span></label>
              <input
                type="text"
                class={inputClass}
                value={settings.offlineFallbackUrl}
                onInput={(e) => setSettings((s) => ({ ...s, offlineFallbackUrl: (e.target as HTMLInputElement).value }))}
                placeholder="/offline.html"
              />
            </div>
          </div>

          {/* Route Rules */}
          <div class="bg-background border border-border rounded-xl p-6 space-y-3">
            <div class="flex items-center justify-between">
              <h3 class="text-sm font-semibold text-text">Route Rules</h3>
              <button
                onClick={addRule}
                class="px-3 py-1.5 rounded-lg text-xs bg-primary text-white hover:bg-primary/90 transition-colors"
              >
                + Add Rule
              </button>
            </div>

            {rules.length === 0 && (
              <p class="text-xs text-text-muted italic">No rules defined. Add a rule to get started.</p>
            )}

            {rules.map((rule, idx) => (
              <div key={rule.id} class="bg-surface border border-border rounded-lg p-4 space-y-3">
                <div class="flex items-center justify-between">
                  <span class="text-xs font-medium text-text-muted">Rule {idx + 1}</span>
                  <button
                    onClick={() => removeRule(rule.id)}
                    class="text-xs text-red-400 hover:text-red-300 transition-colors px-2 py-0.5 rounded hover:bg-red-500/10"
                  >
                    Remove
                  </button>
                </div>

                {/* Pattern */}
                <div>
                  <label class="block text-xs text-text-muted mb-1">Route Pattern</label>
                  <input
                    type="text"
                    class={inputClass}
                    value={rule.pattern}
                    onInput={(e) => updateRule(rule.id, 'pattern', (e.target as HTMLInputElement).value)}
                    placeholder="/api/*, *.css, /images/*"
                  />
                </div>

                {/* Strategy */}
                <div>
                  <label class="block text-xs text-text-muted mb-1">Cache Strategy</label>
                  <select
                    class={inputClass}
                    value={rule.strategy}
                    onChange={(e) => {
                      updateRule(rule.id, 'strategy', (e.target as HTMLSelectElement).value as CacheStrategy);
                      setActiveInfoRule(rule.id);
                    }}
                    onFocus={() => setActiveInfoRule(rule.id)}
                  >
                    {STRATEGIES.map((s) => (
                      <option key={s.value} value={s.value}>
                        {s.label} — {s.description}
                      </option>
                    ))}
                  </select>
                  {activeInfoRule === rule.id && <StrategyInfoCard strategy={rule.strategy} />}
                </div>

                {/* Cache Name */}
                <div>
                  <label class="block text-xs text-text-muted mb-1">Cache Name</label>
                  <input
                    type="text"
                    class={inputClass}
                    value={rule.cacheName}
                    onInput={(e) => updateRule(rule.id, 'cacheName', (e.target as HTMLInputElement).value)}
                    placeholder={deriveCacheName(rule.pattern)}
                  />
                </div>

                {/* Max Age + Max Entries */}
                <div class="grid grid-cols-2 gap-3">
                  <div>
                    <label class="block text-xs text-text-muted mb-1">Max Age <span class="opacity-50">(optional)</span></label>
                    <div class="flex gap-1">
                      <input
                        type="number"
                        class={`${smallInputClass} w-16 flex-shrink-0`}
                        value={rule.maxAge}
                        onInput={(e) => updateRule(rule.id, 'maxAge', (e.target as HTMLInputElement).value)}
                        placeholder="30"
                        min="0"
                      />
                      <select
                        class={`${smallInputClass} flex-1`}
                        value={rule.maxAgeUnit}
                        onChange={(e) => updateRule(rule.id, 'maxAgeUnit', (e.target as HTMLSelectElement).value as AgeUnit)}
                      >
                        <option value="seconds">sec</option>
                        <option value="minutes">min</option>
                        <option value="hours">hrs</option>
                        <option value="days">days</option>
                      </select>
                    </div>
                  </div>
                  <div>
                    <label class="block text-xs text-text-muted mb-1">Max Entries <span class="opacity-50">(optional)</span></label>
                    <input
                      type="number"
                      class={`${smallInputClass} w-full`}
                      value={rule.maxEntries}
                      onInput={(e) => updateRule(rule.id, 'maxEntries', (e.target as HTMLInputElement).value)}
                      placeholder="100"
                      min="0"
                    />
                  </div>
                </div>

                {/* Preview badge */}
                <div class="flex items-center gap-2 pt-1">
                  <span class="text-xs text-text-muted font-mono">{rule.pattern || '(no pattern)'}</span>
                  <span class="text-text-muted">→</span>
                  <StrategyBadge strategy={rule.strategy} />
                  {(rule.cacheName || deriveCacheName(rule.pattern)) && (
                    <span class="text-xs text-text-muted font-mono opacity-60">
                      [{rule.cacheName || deriveCacheName(rule.pattern)}]
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* RIGHT PANEL — Generated SW */}
        <div class="bg-background border border-border rounded-xl p-6 flex flex-col gap-3">
          <div class="flex items-center justify-between flex-wrap gap-2">
            <div class="flex items-center gap-2">
              <h3 class="text-sm font-semibold text-text">Generated sw.js</h3>
              <span class="text-xs text-text-muted bg-surface border border-border rounded px-2 py-0.5">
                {generated.split('\n').length} lines
              </span>
            </div>
            <div class="flex gap-2">
              <button
                onClick={handleCopy}
                class="px-3 py-1.5 rounded-lg text-xs bg-surface border border-border text-text-muted hover:text-text hover:border-primary/50 transition-colors"
              >
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button
                onClick={handleDownload}
                class="px-3 py-1.5 rounded-lg text-xs bg-primary text-white hover:bg-primary/90 transition-colors"
              >
                Download sw.js
              </button>
            </div>
          </div>

          <pre class="bg-surface rounded-lg border border-border p-3 text-xs font-mono text-green-400 overflow-x-auto overflow-y-auto max-h-[680px] whitespace-pre leading-relaxed">
            {generated}
          </pre>

          {/* Usage hint */}
          <div class="bg-surface border border-border rounded-lg p-3 space-y-1">
            <p class="text-xs font-semibold text-text">Usage</p>
            <p class="text-xs text-text-muted">1. Place <code class="text-primary">sw.js</code> in your project root.</p>
            <p class="text-xs text-text-muted">2. Register it in your app:</p>
            <pre class="text-xs font-mono text-green-400 bg-background rounded p-2 mt-1 overflow-x-auto whitespace-pre">{`if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/sw.js');
}`}</pre>
            <p class="text-xs text-text-muted mt-1">3. Bump <code class="text-primary">SW Version</code> when you want users to pick up cache changes.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
