import { useState } from 'preact/hooks';

type StepType = 'activity' | 'timer' | 'signal' | 'condition' | 'parallel' | 'child-workflow';

const STEP_LABELS: Record<StepType, string> = {
  activity: 'Activity (external call)',
  timer: 'Timer (sleep/delay)',
  signal: 'Signal (await event)',
  condition: 'Condition (branch)',
  parallel: 'Parallel (fan-out)',
  'child-workflow': 'Child Workflow',
};

const STEP_ICONS: Record<StepType, string> = {
  activity: '⚡',
  timer: '⏱',
  signal: '📡',
  condition: '⚙',
  parallel: '⬌',
  'child-workflow': '🔄',
};

interface WorkflowStep {
  id: string;
  name: string;
  type: StepType;
  retryMax: number;
  timeout: string;
  description: string;
}

interface WorkflowConfig {
  name: string;
  taskQueue: string;
  language: 'typescript' | 'python' | 'go';
  enableSignals: boolean;
  enableQueries: boolean;
  workflowTimeout: string;
}

function genId() {
  return Math.random().toString(36).slice(2, 8);
}

function generateCode(config: WorkflowConfig, steps: WorkflowStep[]): string {
  const { name, taskQueue, language } = config;
  const wfName = name || 'MyWorkflow';

  if (language === 'typescript') {
    const activityImports = steps
      .filter(s => s.type === 'activity')
      .map(s => s.name || 'myActivity')
      .join(', ');
    const activityDecl = steps
      .filter(s => s.type === 'activity')
      .map(s => {
        const n = s.name || 'myActivity';
        const to = s.timeout || '30s';
        return `  const ${n}Fn = proxyActivities<typeof activities>({
    startToCloseTimeout: '${to}',
    retry: { maximumAttempts: ${s.retryMax || 3} },
  });`;
      })
      .join('\n');

    const stepCode = steps.map((s, i) => {
      if (s.type === 'activity') return `    await ${s.name || 'myActivity'}Fn.${s.name || 'myActivity'}(input);`;
      if (s.type === 'timer') return `    await sleep('${s.timeout || '5m'}'); // ${s.description || 'Wait'}`;
      if (s.type === 'signal') return `    await condition(() => signalReceived, '${s.timeout || '1h'}'); // await signal`;
      if (s.type === 'condition') return `    if (/* ${s.description || 'condition'} */) { /* handle branch */ }`;
      if (s.type === 'parallel') return `    await Promise.all([/* ${s.description || 'parallel tasks'} */]);`;
      if (s.type === 'child-workflow') return `    await executeChild(${s.name || 'ChildWorkflow'}, { taskQueue: '${taskQueue}' });`;
      return '';
    }).join('\n');

    const signalBlock = config.enableSignals ? `
  let signalReceived = false;
  setHandler(mySignal, () => { signalReceived = true; });` : '';

    const queryBlock = config.enableQueries ? `
  setHandler(statusQuery, () => 'running');` : '';

    const signalImport = config.enableSignals ? ', defineSignal, setHandler, condition' : '';
    const queryImport = config.enableQueries ? ', defineQuery, setHandler' : '';

    return `// ${wfName} — Generated by Temporal Workflow Designer
// https://devplaybook.cc/tools/temporal-workflow-designer

import { proxyActivities, sleep, executeChild${signalImport}${queryImport} } from '@temporalio/workflow';
import type * as activities from './activities';

${config.enableSignals ? `export const mySignal = defineSignal('mySignal');` : ''}
${config.enableQueries ? `export const statusQuery = defineQuery<string>('status');` : ''}

export async function ${wfName}(input: unknown): Promise<void> {
${activityDecl ? activityDecl + '\n' : ''}${signalBlock}${queryBlock}

${stepCode}
}`;
  }

  if (language === 'python') {
    const stepCode = steps.map(s => {
      if (s.type === 'activity') return `    await workflow.execute_activity(\n        ${s.name || 'my_activity'},\n        start_to_close_timeout=timedelta(seconds=${parseSecs(s.timeout || '30s')}),\n        retry_policy=RetryPolicy(maximum_attempts=${s.retryMax || 3}),\n    )`;
      if (s.type === 'timer') return `    await asyncio.sleep(${parseSecs(s.timeout || '300s')})  # ${s.description || 'Wait'}`;
      if (s.type === 'signal') return `    await workflow.wait_condition(lambda: self._signal_received)  # await signal`;
      if (s.type === 'condition') return `    if True:  # ${s.description || 'condition'}\n        pass`;
      if (s.type === 'parallel') return `    await asyncio.gather(  # ${s.description || 'parallel'}\n    )`;
      if (s.type === 'child-workflow') return `    await workflow.execute_child_workflow(${s.name || 'ChildWorkflow'}, task_queue="${taskQueue}")`;
      return '';
    }).join('\n');

    return `# ${wfName} — Generated by Temporal Workflow Designer
# https://devplaybook.cc/tools/temporal-workflow-designer

import asyncio
from datetime import timedelta
from temporalio import workflow
from temporalio.common import RetryPolicy


@workflow.defn
class ${wfName}:
    def __init__(self):
        self._signal_received = False

    @workflow.run
    async def run(self, input: dict) -> None:
${stepCode || '        pass'}
`;
  }

  if (language === 'go') {
    const stepCode = steps.map(s => {
      if (s.type === 'activity') return `    if err := workflow.ExecuteActivity(ctx, ${s.name || 'MyActivity'}, input).Get(ctx, nil); err != nil {\n        return err\n    }`;
      if (s.type === 'timer') return `    _ = workflow.Sleep(ctx, ${parseSecs(s.timeout || '300s')} * time.Second)`;
      if (s.type === 'signal') return `    workflow.GetSignalChannel(ctx, "mySignal").Receive(ctx, nil)`;
      if (s.type === 'condition') return `    // ${s.description || 'condition branch'}`;
      if (s.type === 'parallel') return `    // parallel fan-out — use workflow.Go() for goroutines`;
      if (s.type === 'child-workflow') return `    cwo := workflow.ChildWorkflowOptions{TaskQueue: "${taskQueue}"}\n    cctx := workflow.WithChildOptions(ctx, cwo)\n    workflow.ExecuteChildWorkflow(cctx, ${s.name || 'ChildWorkflow'}).Get(ctx, nil)`;
      return '';
    }).join('\n');

    return `// ${wfName} — Generated by Temporal Workflow Designer
// https://devplaybook.cc/tools/temporal-workflow-designer

package workflows

import (
    "go.temporal.io/sdk/workflow"
    "time"
)

func ${wfName}(ctx workflow.Context, input interface{}) error {
    ao := workflow.ActivityOptions{
        StartToCloseTimeout: 30 * time.Second,
    }
    ctx = workflow.WithActivityOptions(ctx, ao)

${stepCode || '    return nil'}
    return nil
}`;
  }

  return '';
}

function parseSecs(val: string): number {
  const m = val.match(/^(\d+)(s|m|h)?$/);
  if (!m) return 30;
  const n = parseInt(m[1]);
  if (m[2] === 'm') return n * 60;
  if (m[2] === 'h') return n * 3600;
  return n;
}

export default function TemporalWorkflowDesigner() {
  const [config, setConfig] = useState<WorkflowConfig>({
    name: 'OrderFulfillmentWorkflow',
    taskQueue: 'order-processing',
    language: 'typescript',
    enableSignals: false,
    enableQueries: false,
    workflowTimeout: '24h',
  });

  const [steps, setSteps] = useState<WorkflowStep[]>([
    { id: genId(), name: 'validateOrder', type: 'activity', retryMax: 3, timeout: '10s', description: 'Validate order details' },
    { id: genId(), name: 'chargePayment', type: 'activity', retryMax: 2, timeout: '30s', description: 'Charge payment method' },
    { id: genId(), name: '', type: 'timer', retryMax: 1, timeout: '5m', description: 'Wait for warehouse confirm' },
    { id: genId(), name: 'shipOrder', type: 'activity', retryMax: 3, timeout: '15s', description: 'Trigger shipping' },
  ]);

  const [copied, setCopied] = useState(false);
  const [activeStep, setActiveStep] = useState<string | null>(null);

  function addStep(type: StepType) {
    setSteps(prev => [...prev, {
      id: genId(),
      name: type === 'activity' ? 'newActivity' : '',
      type,
      retryMax: 3,
      timeout: '30s',
      description: '',
    }]);
  }

  function removeStep(id: string) {
    setSteps(prev => prev.filter(s => s.id !== id));
    if (activeStep === id) setActiveStep(null);
  }

  function updateStep(id: string, patch: Partial<WorkflowStep>) {
    setSteps(prev => prev.map(s => s.id === id ? { ...s, ...patch } : s));
  }

  function moveStep(id: string, dir: -1 | 1) {
    setSteps(prev => {
      const idx = prev.findIndex(s => s.id === id);
      if (idx < 0) return prev;
      const next = [...prev];
      const swap = idx + dir;
      if (swap < 0 || swap >= next.length) return prev;
      [next[idx], next[swap]] = [next[swap], next[idx]];
      return next;
    });
  }

  const code = generateCode(config, steps);

  function copy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const active = steps.find(s => s.id === activeStep);

  return (
    <div class="space-y-6">
      {/* Config Panel */}
      <div class="bg-surface-2 border border-border rounded-xl p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        <div>
          <label class="block text-sm font-medium mb-1">Workflow Name</label>
          <input
            type="text"
            value={config.name}
            onInput={e => setConfig(c => ({ ...c, name: (e.target as HTMLInputElement).value }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Task Queue</label>
          <input
            type="text"
            value={config.taskQueue}
            onInput={e => setConfig(c => ({ ...c, taskQueue: (e.target as HTMLInputElement).value }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Language</label>
          <select
            value={config.language}
            onChange={e => setConfig(c => ({ ...c, language: (e.target as HTMLSelectElement).value as any }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          >
            <option value="typescript">TypeScript</option>
            <option value="python">Python</option>
            <option value="go">Go</option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Workflow Timeout</label>
          <input
            type="text"
            value={config.workflowTimeout}
            onInput={e => setConfig(c => ({ ...c, workflowTimeout: (e.target as HTMLInputElement).value }))}
            placeholder="e.g. 24h"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div class="flex items-center gap-4 pt-4">
          <label class="flex items-center gap-2 text-sm cursor-pointer">
            <input
              type="checkbox"
              checked={config.enableSignals}
              onChange={e => setConfig(c => ({ ...c, enableSignals: (e.target as HTMLInputElement).checked }))}
              class="rounded"
            />
            Signals
          </label>
          <label class="flex items-center gap-2 text-sm cursor-pointer">
            <input
              type="checkbox"
              checked={config.enableQueries}
              onChange={e => setConfig(c => ({ ...c, enableQueries: (e.target as HTMLInputElement).checked }))}
              class="rounded"
            />
            Queries
          </label>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Workflow Steps Builder */}
        <div>
          <div class="flex items-center justify-between mb-3">
            <h2 class="font-semibold text-sm uppercase tracking-wide text-text-muted">Workflow Steps ({steps.length})</h2>
          </div>

          {/* Steps list */}
          <div class="space-y-2 mb-4">
            {steps.map((step, i) => (
              <div
                key={step.id}
                onClick={() => setActiveStep(step.id === activeStep ? null : step.id)}
                class={`bg-surface-2 border rounded-lg p-3 cursor-pointer transition-colors ${activeStep === step.id ? 'border-accent' : 'border-border hover:border-accent/50'}`}
              >
                <div class="flex items-center gap-2">
                  <span class="text-base">{STEP_ICONS[step.type]}</span>
                  <span class="text-sm font-medium flex-1 truncate">{step.name || STEP_LABELS[step.type]}</span>
                  <span class="text-xs text-text-muted bg-surface px-2 py-0.5 rounded-full">{step.type}</span>
                  <div class="flex gap-1" onClick={e => e.stopPropagation()}>
                    <button
                      onClick={() => moveStep(step.id, -1)}
                      disabled={i === 0}
                      class="text-xs px-1.5 py-0.5 rounded hover:bg-surface disabled:opacity-30"
                    >▲</button>
                    <button
                      onClick={() => moveStep(step.id, 1)}
                      disabled={i === steps.length - 1}
                      class="text-xs px-1.5 py-0.5 rounded hover:bg-surface disabled:opacity-30"
                    >▼</button>
                    <button
                      onClick={() => removeStep(step.id)}
                      class="text-xs px-1.5 py-0.5 rounded hover:bg-red-500/20 text-red-400"
                    >✕</button>
                  </div>
                </div>
                {step.description && (
                  <p class="text-xs text-text-muted mt-1 pl-7">{step.description}</p>
                )}
              </div>
            ))}
          </div>

          {/* Edit panel */}
          {active && (
            <div class="bg-surface-2 border border-accent/30 rounded-xl p-4 mb-4 space-y-3">
              <h3 class="text-sm font-semibold">Edit: {active.name || active.type}</h3>
              {(active.type === 'activity' || active.type === 'child-workflow') && (
                <div>
                  <label class="block text-xs text-text-muted mb-1">Name</label>
                  <input
                    type="text"
                    value={active.name}
                    onInput={e => updateStep(active.id, { name: (e.target as HTMLInputElement).value })}
                    class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                  />
                </div>
              )}
              <div>
                <label class="block text-xs text-text-muted mb-1">Description</label>
                <input
                  type="text"
                  value={active.description}
                  onInput={e => updateStep(active.id, { description: (e.target as HTMLInputElement).value })}
                  class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                />
              </div>
              {active.type !== 'condition' && active.type !== 'parallel' && (
                <div class="grid grid-cols-2 gap-2">
                  <div>
                    <label class="block text-xs text-text-muted mb-1">Timeout</label>
                    <input
                      type="text"
                      value={active.timeout}
                      onInput={e => updateStep(active.id, { timeout: (e.target as HTMLInputElement).value })}
                      placeholder="30s / 5m / 1h"
                      class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                    />
                  </div>
                  {active.type === 'activity' && (
                    <div>
                      <label class="block text-xs text-text-muted mb-1">Max Retries</label>
                      <input
                        type="number"
                        value={active.retryMax}
                        onInput={e => updateStep(active.id, { retryMax: parseInt((e.target as HTMLInputElement).value) || 1 })}
                        min="1" max="10"
                        class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                      />
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Add step buttons */}
          <div>
            <p class="text-xs text-text-muted mb-2">Add Step:</p>
            <div class="flex flex-wrap gap-2">
              {(Object.keys(STEP_LABELS) as StepType[]).map(type => (
                <button
                  key={type}
                  onClick={() => addStep(type)}
                  class="text-xs bg-surface border border-border rounded-lg px-2.5 py-1.5 hover:border-accent hover:text-accent transition-colors"
                >
                  {STEP_ICONS[type]} {type}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Code Output */}
        <div>
          <div class="flex items-center justify-between mb-3">
            <h2 class="font-semibold text-sm uppercase tracking-wide text-text-muted">Generated Code</h2>
            <button
              onClick={copy}
              class="text-xs bg-accent text-white rounded-lg px-3 py-1.5 hover:bg-accent/90 transition-colors"
            >
              {copied ? '✓ Copied' : 'Copy Code'}
            </button>
          </div>
          <pre class="bg-surface border border-border rounded-xl p-4 text-xs font-mono overflow-x-auto overflow-y-auto max-h-[500px] whitespace-pre leading-relaxed text-text-muted">
            <code>{code}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
