import { useState } from 'preact/hooks';

type TriggerType = 'event' | 'scheduled' | 'webhook' | 'dynamic';
type TaskType = 'regular' | 'subtask' | 'wait' | 'delay' | 'retry';
type Runtime = 'nodejs' | 'python' | 'bun';

interface JobTask {
  id: string;
  type: TaskType;
  name: string;
  description: string;
  delayDuration: string;
  retryAttempts: number;
}

interface JobConfig {
  id: string;
  name: string;
  triggerType: TriggerType;
  eventName: string;
  cronSchedule: string;
  maxDuration: number;
  retryAttempts: number;
  queue: string;
  runtime: Runtime;
  machine: string;
}

const TASK_LABELS: Record<TaskType, string> = {
  regular: 'task.run (execute step)',
  subtask: 'subtask (background task)',
  wait: 'wait.forEvent (await event)',
  delay: 'wait.for (delay)',
  retry: 'retry block',
};

const TASK_ICONS: Record<TaskType, string> = {
  regular: '▶',
  subtask: '⬡',
  wait: '⏳',
  delay: '💤',
  retry: '🔄',
};

function genId() {
  return Math.random().toString(36).slice(2, 8);
}

function generateCode(config: JobConfig, tasks: JobTask[]): string {
  const { runtime } = config;
  const jobId = config.id || 'my-job';
  const jobName = config.name || 'My Job';

  if (runtime === 'nodejs' || runtime === 'bun') {
    const triggerBlock = config.triggerType === 'event'
      ? `  trigger: triggersFrom.staticPoint({ event: "${config.eventName || 'user.signup'}" }),`
      : config.triggerType === 'scheduled'
      ? `  trigger: schedules.cron("${config.cronSchedule || '0 9 * * *'}"),`
      : config.triggerType === 'webhook'
      ? `  trigger: triggersFrom.webhook({ source: "webhook" }),`
      : `  trigger: triggersFrom.dynamicSchedule(),`;

    const machineBlock = config.machine && config.machine !== 'micro'
      ? `  machine: "${config.machine}",\n` : '';
    const queueBlock = config.queue
      ? `  queue: { name: "${config.queue}" },\n` : '';
    const maxDurBlock = config.maxDuration !== 300
      ? `  maxDuration: ${config.maxDuration},\n` : '';
    const retryBlock = config.retryAttempts !== 3
      ? `  retry: { maxAttempts: ${config.retryAttempts} },\n` : '';

    const taskCode = tasks.map(t => {
      if (t.type === 'regular') {
        return `  await task.run("${t.name || 'step'}", async () => {
    // ${t.description || 'Task logic here'}
    return { success: true };
  });`;
      }
      if (t.type === 'subtask') {
        return `  const subtaskHandle = await ${t.name || 'mySubtask'}.triggerAndWait({
    payload: { /* data */ },
  });
  // ${t.description || 'Fire and wait for subtask'}`;
      }
      if (t.type === 'wait') {
        return `  const signal = await wait.forEvent("${t.name || 'my-signal'}", {
    event: "${t.description || 'user.confirmed'}",
    timeout: "${t.delayDuration || '1h'}",
  });`;
      }
      if (t.type === 'delay') {
        return `  await wait.for({ seconds: ${parseSecs(t.delayDuration || '60s')} }); // ${t.description || 'Delay'}`;
      }
      if (t.type === 'retry') {
        return `  // Retry block (${t.retryAttempts || 3} attempts)
  // task.run() has built-in retries via job-level config`;
      }
      return '';
    }).join('\n\n');

    const importLine = runtime === 'bun'
      ? `import { task, wait, schedules, triggersFrom } from "@trigger.dev/sdk/v3";`
      : `import { task, wait, schedules, triggersFrom } from "@trigger.dev/sdk/v3";`;

    return `// ${jobName} — Generated by Trigger.dev Job Creator
// https://devplaybook.cc/tools/triggerdev-job-creator

${importLine}

export const ${jobId.replace(/-/g, '_')} = task({
  id: "${jobId}",
${triggerBlock}
${machineBlock}${queueBlock}${maxDurBlock}${retryBlock}  run: async (payload, { ctx }) => {
${taskCode || '    // Add tasks above'}

    return { message: "Job completed" };
  },
});`;
  }

  if (runtime === 'python') {
    const triggerDecorator = config.triggerType === 'scheduled'
      ? `@task(id="${jobId}", schedule=CronTrigger("${config.cronSchedule || '0 9 * * *'}"), max_duration=${config.maxDuration})`
      : `@task(id="${jobId}", max_duration=${config.maxDuration})`;

    const taskCode = tasks.map(t => {
      if (t.type === 'regular') {
        return `    # ${t.description || 'Task logic'}
    result = await run_task_step("${t.name || 'step'}", lambda: {"success": True})`;
      }
      if (t.type === 'delay') {
        return `    await asyncio.sleep(${parseSecs(t.delayDuration || '60s')})  # ${t.description || 'Delay'}`;
      }
      if (t.type === 'wait') {
        return `    signal = await wait_for_event("${t.description || 'user.confirmed'}", timeout="${t.delayDuration || '1h'}")`;
      }
      return `    # ${t.type}: ${t.description}`;
    }).join('\n\n');

    return `# ${jobName} — Generated by Trigger.dev Job Creator
# https://devplaybook.cc/tools/triggerdev-job-creator

import asyncio
from trigger_sdk import task, CronTrigger


${triggerDecorator}
async def ${jobId.replace(/-/g, '_')}(payload: dict) -> dict:
${taskCode || '    # Add tasks above'}

    return {"message": "Job completed"}`;
  }

  return '';
}

function parseSecs(val: string): number {
  const m = val.match(/^(\d+)(s|m|h)?$/);
  if (!m) return 60;
  const n = parseInt(m[1]);
  if (m[2] === 'm') return n * 60;
  if (m[2] === 'h') return n * 3600;
  return n;
}

export default function TriggerdevJobCreator() {
  const [config, setConfig] = useState<JobConfig>({
    id: 'send-welcome-email',
    name: 'Send Welcome Email',
    triggerType: 'event',
    eventName: 'user.signup',
    cronSchedule: '0 9 * * *',
    maxDuration: 300,
    retryAttempts: 3,
    queue: '',
    runtime: 'nodejs',
    machine: 'micro',
  });

  const [tasks, setTasks] = useState<JobTask[]>([
    { id: genId(), type: 'regular', name: 'fetch-user', description: 'Load user profile from database', delayDuration: '', retryAttempts: 3 },
    { id: genId(), type: 'regular', name: 'render-email', description: 'Render email template with user data', delayDuration: '', retryAttempts: 3 },
    { id: genId(), type: 'delay', name: '', description: 'Brief delay before sending', delayDuration: '5s', retryAttempts: 1 },
    { id: genId(), type: 'regular', name: 'send-email', description: 'Send via Resend/SendGrid', delayDuration: '', retryAttempts: 3 },
  ]);

  const [copied, setCopied] = useState(false);
  const [activeTask, setActiveTask] = useState<string | null>(null);

  function addTask(type: TaskType) {
    setTasks(prev => [...prev, { id: genId(), type, name: '', description: '', delayDuration: '60s', retryAttempts: 3 }]);
  }

  function removeTask(id: string) {
    setTasks(prev => prev.filter(t => t.id !== id));
    if (activeTask === id) setActiveTask(null);
  }

  function updateTask(id: string, patch: Partial<JobTask>) {
    setTasks(prev => prev.map(t => t.id === id ? { ...t, ...patch } : t));
  }

  function moveTask(id: string, dir: -1 | 1) {
    setTasks(prev => {
      const idx = prev.findIndex(t => t.id === id);
      if (idx < 0) return prev;
      const next = [...prev];
      const swap = idx + dir;
      if (swap < 0 || swap >= next.length) return prev;
      [next[idx], next[swap]] = [next[swap], next[idx]];
      return next;
    });
  }

  const code = generateCode(config, tasks);

  function copy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const active = tasks.find(t => t.id === activeTask);

  return (
    <div class="space-y-6">
      {/* Config Panel */}
      <div class="bg-surface-2 border border-border rounded-xl p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        <div>
          <label class="block text-sm font-medium mb-1">Job ID</label>
          <input
            type="text"
            value={config.id}
            onInput={e => setConfig(c => ({ ...c, id: (e.target as HTMLInputElement).value }))}
            placeholder="my-job"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Job Name</label>
          <input
            type="text"
            value={config.name}
            onInput={e => setConfig(c => ({ ...c, name: (e.target as HTMLInputElement).value }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Runtime</label>
          <select
            value={config.runtime}
            onChange={e => setConfig(c => ({ ...c, runtime: (e.target as HTMLSelectElement).value as any }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          >
            <option value="nodejs">Node.js</option>
            <option value="bun">Bun</option>
            <option value="python">Python</option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Trigger Type</label>
          <select
            value={config.triggerType}
            onChange={e => setConfig(c => ({ ...c, triggerType: (e.target as HTMLSelectElement).value as any }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          >
            <option value="event">Event</option>
            <option value="scheduled">Scheduled (Cron)</option>
            <option value="webhook">Webhook</option>
            <option value="dynamic">Dynamic Schedule</option>
          </select>
        </div>
        {config.triggerType === 'event' || config.triggerType === 'webhook' ? (
          <div>
            <label class="block text-sm font-medium mb-1">Event Name</label>
            <input
              type="text"
              value={config.eventName}
              onInput={e => setConfig(c => ({ ...c, eventName: (e.target as HTMLInputElement).value }))}
              placeholder="user.signup"
              class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
            />
          </div>
        ) : config.triggerType === 'scheduled' ? (
          <div>
            <label class="block text-sm font-medium mb-1">Cron Schedule</label>
            <input
              type="text"
              value={config.cronSchedule}
              onInput={e => setConfig(c => ({ ...c, cronSchedule: (e.target as HTMLInputElement).value }))}
              placeholder="0 9 * * *"
              class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
            />
          </div>
        ) : null}
        <div>
          <label class="block text-sm font-medium mb-1">Max Duration (seconds)</label>
          <input
            type="number"
            value={config.maxDuration}
            onInput={e => setConfig(c => ({ ...c, maxDuration: parseInt((e.target as HTMLInputElement).value) || 300 }))}
            min="1"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Retry Attempts</label>
          <input
            type="number"
            value={config.retryAttempts}
            onInput={e => setConfig(c => ({ ...c, retryAttempts: parseInt((e.target as HTMLInputElement).value) || 0 }))}
            min="0" max="20"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Machine Type</label>
          <select
            value={config.machine}
            onChange={e => setConfig(c => ({ ...c, machine: (e.target as HTMLSelectElement).value }))}
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          >
            <option value="micro">micro (0.25 CPU, 256MB)</option>
            <option value="small-1x">small-1x (0.5 CPU, 512MB)</option>
            <option value="small-2x">small-2x (1 CPU, 1GB)</option>
            <option value="medium-1x">medium-1x (1 CPU, 2GB)</option>
            <option value="large-1x">large-1x (2 CPU, 4GB)</option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Queue Name (optional)</label>
          <input
            type="text"
            value={config.queue}
            onInput={e => setConfig(c => ({ ...c, queue: (e.target as HTMLInputElement).value }))}
            placeholder="email-queue"
            class="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-accent"
          />
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Tasks */}
        <div>
          <h2 class="font-semibold text-sm uppercase tracking-wide text-text-muted mb-3">Job Tasks ({tasks.length})</h2>

          <div class="space-y-2 mb-4">
            {tasks.map((task, i) => (
              <div
                key={task.id}
                onClick={() => setActiveTask(task.id === activeTask ? null : task.id)}
                class={`bg-surface-2 border rounded-lg p-3 cursor-pointer transition-colors ${activeTask === task.id ? 'border-accent' : 'border-border hover:border-accent/50'}`}
              >
                <div class="flex items-center gap-2">
                  <span class="text-sm">{TASK_ICONS[task.type]}</span>
                  <span class="text-sm font-medium flex-1 truncate">{task.name || task.type}</span>
                  <span class="text-xs text-text-muted bg-surface px-2 py-0.5 rounded-full">{task.type}</span>
                  <div class="flex gap-1" onClick={e => e.stopPropagation()}>
                    <button onClick={() => moveTask(task.id, -1)} disabled={i === 0} class="text-xs px-1.5 py-0.5 rounded hover:bg-surface disabled:opacity-30">▲</button>
                    <button onClick={() => moveTask(task.id, 1)} disabled={i === tasks.length - 1} class="text-xs px-1.5 py-0.5 rounded hover:bg-surface disabled:opacity-30">▼</button>
                    <button onClick={() => removeTask(task.id)} class="text-xs px-1.5 py-0.5 rounded hover:bg-red-500/20 text-red-400">✕</button>
                  </div>
                </div>
                {task.description && <p class="text-xs text-text-muted mt-1 pl-5">{task.description}</p>}
              </div>
            ))}
          </div>

          {active && (
            <div class="bg-surface-2 border border-accent/30 rounded-xl p-4 mb-4 space-y-3">
              <h3 class="text-sm font-semibold">Edit: {active.name || active.type}</h3>
              {active.type !== 'delay' && (
                <div>
                  <label class="block text-xs text-text-muted mb-1">Task Name</label>
                  <input
                    type="text"
                    value={active.name}
                    onInput={e => updateTask(active.id, { name: (e.target as HTMLInputElement).value })}
                    class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                  />
                </div>
              )}
              <div>
                <label class="block text-xs text-text-muted mb-1">
                  {active.type === 'wait' ? 'Event Name to Wait For' : 'Description'}
                </label>
                <input
                  type="text"
                  value={active.description}
                  onInput={e => updateTask(active.id, { description: (e.target as HTMLInputElement).value })}
                  class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                />
              </div>
              {(active.type === 'delay' || active.type === 'wait') && (
                <div>
                  <label class="block text-xs text-text-muted mb-1">Duration / Timeout</label>
                  <input
                    type="text"
                    value={active.delayDuration}
                    onInput={e => updateTask(active.id, { delayDuration: (e.target as HTMLInputElement).value })}
                    placeholder="30s / 5m / 1h"
                    class="w-full bg-surface border border-border rounded px-2 py-1.5 text-sm"
                  />
                </div>
              )}
            </div>
          )}

          <div>
            <p class="text-xs text-text-muted mb-2">Add Task:</p>
            <div class="flex flex-wrap gap-2">
              {(Object.keys(TASK_LABELS) as TaskType[]).map(type => (
                <button
                  key={type}
                  onClick={() => addTask(type)}
                  class="text-xs bg-surface border border-border rounded-lg px-2.5 py-1.5 hover:border-accent hover:text-accent transition-colors"
                >
                  {TASK_ICONS[type]} {type}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Code Output */}
        <div>
          <div class="flex items-center justify-between mb-3">
            <h2 class="font-semibold text-sm uppercase tracking-wide text-text-muted">Generated Code</h2>
            <button
              onClick={copy}
              class="text-xs bg-accent text-white rounded-lg px-3 py-1.5 hover:bg-accent/90 transition-colors"
            >
              {copied ? '✓ Copied' : 'Copy Code'}
            </button>
          </div>
          <pre class="bg-surface border border-border rounded-xl p-4 text-xs font-mono overflow-x-auto overflow-y-auto max-h-[500px] whitespace-pre leading-relaxed text-text-muted">
            <code>{code}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
